### ISSUE TITLE
pct_dropout for cells

### ISSUE THREAD

**Issue by lazappi** [alanocallaghan/scater#1]
I've just noticed that `calculateQCMetrics` no longer calculates dropout percentage for cells. Would it be possible to bring that back? If not it should probably be removed from the function documentation.

Thanks

**Comment by jenzopr** [comment]
In the meantime, I do `colData(sceData)$pct_dropout <- 1 - apply(assay(sceData, "is_exprs"), 2, mean))`...

**Comment by LTLA** [comment]
We do have a `pct_dropout_X` field, where X is whatever `exprs_values` was set to. The suffix is necessary as one could theoretically force the function to yield different % drop-out estimates depending on the values, detection limit, etc. Hence the need for disambiguation.

I was actually going to remove this field, but I guess people find it useful, so I'll leave it in.

**Comment by jenzopr** [comment]
Thanks, Aaron!
