### ISSUE TITLE
function logNormCounts cannot be found after scater installation

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [alanocallaghan/scater#100]
![1](https://user-images.githubusercontent.com/51248547/68290662-2ca16080-003d-11ea-90ef-dce7615a7a99.png)
![2](https://user-images.githubusercontent.com/51248547/68290672-2e6b2400-003d-11ea-94dc-91a3be805f97.png)

Hi,
I installed the scater package on HPC. The installation went smoothly. However, when I tried to use logNormCounts function, it showed that the function cannot be found. I used lsf.str("package:scater") to check functions in package. I did not find logNormCounts function. It was really weird, as things went well with Rstudo in my pc. 
Could you please help me figure out how to install/use logNormCounts function properly on HPC?

I also tried to use log2(normalizeCounts) to substitute  logNormCounts. But, normalizeCounts returned me a Large dgCMatrix, while logNormCounts should give back a Large SingleCellExperiment which is supposed to be used in the following SingleR step.

If installation of logNormCounts doesn't work, any idea to use other ways to get through?

Thanks!

**Comment by LTLA** [comment]
What's your `sessionInfo()`? Make sure you're using the [latest version of _scater_](https://bioconductor.org/packages/release/bioc/html/scater.html).

**Comment by XiaofeiSunUCSF** [comment]
Hi,

When I tried to install the latest version, I got another error. 
![image](https://user-images.githubusercontent.com/51248547/68343646-1f6a8d00-00a2-11ea-919b-5f583300b5ce.png)
could you please help me figured out

**Comment by LTLA** [comment]
It looks like you don't have the latest version of _BiocSingular_. Recall that Bioconductor operates as a cohort, so _scater_ expects to get the version of _BiocSingular_ in Bioconductor version 3.10.

**Comment by XiaofeiSunUCSF** [comment]
Thank you for your help. The installation of scater is solved!!Thanks.
I met another problem when using SingleCellExperiment.
![image](https://user-images.githubusercontent.com/51248547/68368083-14d4e580-00ec-11ea-9539-6d63af8a8f53.png)
I google it. someone said that might be related to S4Vectors. I noticed you are one of the developer for S4Vectors also. Do you have any idea about this error?
![image](https://user-images.githubusercontent.com/51248547/68368133-30d88700-00ec-11ea-9799-780e2e7280a0.png)
Thanks again for your help

**Comment by LTLA** [comment]
This occasionally happens if you manually install package dependencies rather than allowing `BiocManager` to do the installation. Follow the advice here:

https://support.bioconductor.org/p/101813/#102033

**Comment by XiaofeiSunUCSF** [comment]
Hi, 
Many thanks for your quick response.
Yes, you are right. I installed the packages manually. I tried to use R on Unix HPC (things always went wrong on Unix HPC. All the packages you developed works very well on my own pc with Rstudio). I found when I used BiocManager to install packages, the packages are not the lastest one.
![image](https://user-images.githubusercontent.com/51248547/68370034-726b3100-00f0-11ea-8941-e7bbcdd709ed.png)(This is from BiocManager)
![image](https://user-images.githubusercontent.com/51248547/68370172-b8c09000-00f0-11ea-9fe6-5205444d8c4c.png) (all the tar.gz file is installed manually)

Since BiocManager sometimes could not install the new package, so I tried to install manually(inspired by you regarding the very beginning question about scater installation. Thank you for your advice)

![11111111111](https://user-images.githubusercontent.com/51248547/68369881-2ae4a500-00f0-11ea-98fc-e7abf10fbcfc.png)
Sometimes I got error "installation path not writeable". I guess that probably because I module R from HPC and do not have access to it? Setting up R on HPC is really annoying!!

I followed your post on Bioconductor
![image](https://user-images.githubusercontent.com/51248547/68372096-0e973700-00f5-11ea-97b6-be75ea6a94bc.png)
tired to reinstall all the pacakges
![image](https://user-images.githubusercontent.com/51248547/68372217-47cfa700-00f5-11ea-9d64-871ac1b34e10.png)
finally got errors here
![image](https://user-images.githubusercontent.com/51248547/68372458-bf9dd180-00f5-11ea-8377-5cbd3c157557.png)

**Comment by LTLA** [comment]
The real problem is that `BiocManager::version()` does not give "3.10". As long as this is the case, you will be fighting an uphill battle trying to get the right versions of all the packages.

The solution is to make sure your Bioconductor package is up to date. In theory, this should be as simple as running `BiocManager::install(version="3.10")`, so you could try that.

In practice, I have sometimes found it necessary to do something like:

```r
remove.packages("BiocVersion")
BiocManager::install()
```

... to force it to "forget" the old BioC version and upgrade to the latest one. But this will only work if you have write access to the R installation directory, so that's something for sysadmins to do.

In general, you really should gently prod your sysadmin to upgrade your R installation, otherwise every single user on your HPC will be struggling with the exact same problem.

**Comment by XiaofeiSunUCSF** [comment]
I contact our HPC sysadmins and install version3.10 of BiocManager. All errors finally disappear. Thank you so much guide me make it out. I really appreciate! After several days setting up R on HPC, I can finally run the scRNAseq data
