### ISSUE TITLE
aggregateAcrossCells by QC metric

### ISSUE THREAD

**Issue by alexvpickering** [alanocallaghan/scater#104]
This is something that I am thinking about implementing and am curious as to your thoughts on usefulness/approach. The basic idea would be to have `aggregateAcrossCells` aggregate cells across samples such that the distribution of a particular QC metric (e.g. mitochondrial percentage) is equivalent between samples by using a subset of cells. The desire would be to remove potential quality confounds for subsequent pseudo-bulk differential expression analysis. 

I have a particular set of samples where e.g. the mitochondrial percentage is generally higher and ribosomal percentage lower in the test samples than in the control samples and am thinking about implementing this.

Any thoughts or interest in a PR on this?

**Comment by LTLA** [comment]
> aggregate cells across samples

I assume you mean "within samples" here.

> The desire would be to remove potential quality confounds for subsequent pseudo-bulk differential expression analysis.

Well, it's not an obviously crazy idea. But I will point out some implicit assumptions:

- The differences in those metrics are not biologically driven. We assume this all the time when we do QC, and every time I think I about it, I stare out the window and wonder whether this is correct.
- The QC metrics are close enough to the problem that equalizing them removes the difference, i.e., differences in the QC metrics are not merely a symptom of a more systematic bias.

> Any thoughts or interest in a PR on this?

Possibly. But you will have to figure out how to handle situations where there are no overlaps in the QC distribution between samples, where it is impossible to find a decent subset of cells in a common interval of QC values. Power loss will be considerable if we have to throw out many cells. Even in a common interval, you will have to adjust for differences in the shape of the distribution (e.g., a common interval with a left tail will differ from that with a right tail).

If I were to do this, I would create a histogram for each sample with known breaks, take the minimum density across samples for each bin, and then compute a weight for each bin in each sample as the ratio of the minimum density to the density in that sample. The weight would then be used to compute a weighted average in `sumCountsAcrossCells` (and thus `aggregateAcrossCells`). Not quite preserving the discrete count, but whatever, **edgeR** should be able to deal with it.

You can see that this provides a relatively smooth generalization of your common subset idea, (i) without the need to explicitly define consistent thresholds and (ii) automatically adjusting for differences in the distribution shape. Perhaps you were already considering something like this. Obviously this will fail if the minimum density is zero for all bins, but this entire idea falls apart at that point, so it might be fine if you just spit out a bunch of errors.

In any case, this would not be a direct modification to `aggregateAcrossCells`. Rather, one would write a separate function to compute the weights that would then get passed into `aggregateAcrossCells` and `sumCountsAcrossCells`. This would allow us to change the weighting scheme or add different schemes in the future without hard-coding it into a low-level function.

**Comment by alexvpickering** [comment]
Thank you for the thoughts. I'll put something together.

> The differences in those metrics are not biologically driven. We assume this all the time when we do QC, and every time I think I about it, I stare out the window and wonder whether this is correct.

It might just be the particular set of samples I'm working with, but I feel more at ease with this. I repeatedly see the same situation: a set of clusters with high mitochondrial percentage, low ribosomal percentage, low log10(sum) and low log10(detected). These clusters will segregate from a larger cluster with the same sample-wide marker genes but when the two clusters are directly compared the marker genes are mitochondrial and ribosomal. If that's not the case I stare a bit more ...
