### ISSUE TITLE
Cannot find percellqcMetrics

### ISSUE THREAD

**Issue by ghost** [alanocallaghan/scater#109]
In any version of Scater (bioconductor version, official github, development, or this version) I cannot find the perCellQCMetrics function. I downloaded and tested this package and received this error. Any guidance of what this means or why I cannot find the PerCellQCMetrics function would be greatly appreciated.

Testing scater
Error in altExp(sce, "Spikes") <- SingleCellExperiment(list(counts = spike.data)) : 
  could not find function "altExp<-"
Calls: <Anonymous> ... source_dir -> lapply -> FUN -> eval -> eval -> mockSCE
In addition: Warning messages:
1: object ‘bsparam’ is not exported by 'namespace:BiocSingular' 
2: object ‘make_zero_col_DFrame’ is not exported by 'namespace:S4Vectors' 
3: object ‘altExp<-’ is not exported by 'namespace:SingleCellExperiment' 
4: object ‘altExps<-’ is not exported by 'namespace:SingleCellExperiment' 
5: object ‘altExp’ is not exported by 'namespace:SingleCellExperiment' 
6: object ‘altExpNames’ is not exported by 'namespace:SingleCellExperiment' 
7: object ‘altExps’ is not exported by 'namespace:SingleCellExperiment' 
8: class "DFrame" is not exported by 'namespace:S4Vectors' 
Execution halted

**Comment by LTLA** [comment]
Check that your installation is valid with `BiocManager::valid()` and fix any problems.

**Comment by ghost** [comment]
Hi thanks for the quick reply, I have reinstalled all packages that BiocManager::valid() pointed to as outdated, now it returns [1] TRUE, whereby I reinstall scran (
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("scater"). 
I still am not able to recover the PerCellQCMetrics function, although the scater library seems successfully loaded (scater:: returns a list of functions via tab). Was there something special about this function? I am also unable to recover addPerCellQC or addPerFeatureQC. Possibly I'm downloading an old version of scater? Thanks for the help with troubleshooting.

**Comment by LTLA** [comment]
Well, showing your `sessionInfo()` would be a start.

**Comment by ghost** [comment]
Yes sorry for the imprecise question. As of last writing I have tried to run R with sudo and install everything clean. Turns out I can recover the function at this point and sessioninfo shows 1.4.6 or something, whereas the sessioninfo from which I was working was 1.2 or something near. I'm currently trying to update Bioconductor and R to 4.0 and will report back. Thanks again for the quick responses!

**Comment by ghost** [comment]
Hi Aaron Lun,
Thanks for the input and sorry for wasting your time, next time I will definitely have a better question, I learned a new trick with BiocManager::valid()! It took a while but the underlying problem was I just had an old version of bioconductor which downloaded an old version of scater that did not have the function. I got 1.14.6 now and it works! A fan since Biostars array days! Cheers
