### ISSUE TITLE
multiplot return value is null

### ISSUE THREAD

**Issue by alanocallaghan** [alanocallaghan/scater#114]
Docs say it returns a ggplot2 object; it just draws things on grid viewports.

Three options:
1. Use patchwork, egg or cowplot
1. Use gridExtra and arrangeGrob with a thin s3 class with a print method that draws on the current device
1. Use option 2 if option 1 is not available

**Comment by LTLA** [comment]
Yes, I have been wondering what we should do with this function given that `gridExtra::grid.arrange` basically does the same thing. Happy to go with what you decide; if we use **cowplot**, we should probably promote that to an `Imports:`.
