### ISSUE TITLE
Better support for referencing based on gene symbols

### ISSUE THREAD

**Issue by LTLA** [alanocallaghan/scater#116]
For all the plotting functions, we should add a `swap_rownames=` argument that allows people to swap the row names with a `rowData` field of choice. This would enable quick referencing of genes by their symbols while still retaining Ensembl IDs in the row names of the input SCE for the rest of the analysis.

Of course, one could swap the row names in the SCE before input but this (i) is lossy and (ii) interferes with downstream steps that rely on Ensembl IDs for stable cross-referencing.

Tagging @Alanocallaghan, but I guess you're watching this repo anyway.

**Comment by alanocallaghan** [comment]
This is a really good idea, it's something I end up spending a reasonable amount of time doing when making figures anyway.

Seems like it should go in `.incorporate_common_vis_col` and/or `retrieveCellInfo`

**Comment by LTLA** [comment]
Yes. The exception is for functions that also take feature names in other arguments, e.g., `plotExpression` and `plotHeatmap`, which will need some special handling. That's not a big deal, just something to remember.

Want to get started on the visual parameters for now?

**Comment by alanocallaghan** [comment]
Yeah I'll have a crack today

**Comment by alanocallaghan** [comment]
Need to add a better error when the column isn't found, and might be good to check if there's any duplicated/missing labels. At the moment the behaviour is just to pass everything through

**Comment by LTLA** [comment]
Close. I was thinking that `swap_rownames=` would allow people to pass in gene symbols in `colour_by=` and `features=` and so on, which makes the plotting functions easier to use.

The current implementation of `swap_rownames` is purely aesthetic, replacing the Ensembl ID with the gene symbol; and that's half the battle, but we should also try to win the other half as well.

One could implement `swap_rownames` to _literally_ swap the row names of `object` at the start of the function, and then the rest of the function proceeds with the swapped row names as if they were there at the start.

Some documentation would have to be written about how newly duplicate rownames are handled but SEs support duplicate row names anyway, so it's not like it's a deal-breaker. Though we would need to protect against `NA`s.

FYI better to make these things as PRs so that we can iron out the implementation and squash everything into a single commit at the end. Then the Git history makes it seem like we knew what we were doing all along!

**Comment by alanocallaghan** [comment]
Ah I see what you mean, yeah that's a bit nicer. I'll switch it, I don't think it'll be too tricky - mainly swapping the match.

The commit's on a branch (`gene-ids`), not master. Unless it's something I know is super minor I work with branches. Didn't make the PR yet as I didn't consider it finished

**Comment by LTLA** [comment]
Oh excellent, I didn't notice. 

Also you have a typo on `plotHeatmap` line 15.
