### ISSUE TITLE
How to control colors with scater package?

### ISSUE THREAD

**Issue by ilcink** [alanocallaghan/scater#117]
Hi!

How can one manually select colors of clusters/(labels in case of colour_by="label") e.g. manually attribute colors "#ffcc00", "#ff6633", "#cc0000", "#993300", "#66ffcc" to clusters 1, 2, 3, 4, 5  in

scater::plotReducedDim(sc_data, "TSNE_40", colour_by = "cluster", point_size = 1, text_by="cluster") 

Simple adding scale_color_manual() 

scater::plotReducedDim(sc_data, "TSNE_40", colour_by = "cluster", point_size = 1, text_by="cluster")  + scale_color_manual(values=c("#ffcc00", "#ff6633", "#cc0000", "#993300", "#66ffcc"))

lacks values/clusters interconnection and doesn't work.

Same question for plotExpression : 

scater::plotExpression(sc_data, features = c("ABCD", "EFGH"), x = "cluster", colour_by = "cluster") + scale_color_manual()

**Comment by alanocallaghan** [comment]
Try `scale_fill_manual` or `scale_colour_manual([...], aesthetics="fill")`.

If I interpret 
>lacks values/clusters interconnection

correctly and you want to specify which colour each cluster would be, you have to specify that using `scale_colour_manual`. There's an example below

``` r
library("scater")
example_sce <- mockSCE()
example_sce <- logNormCounts(example_sce)
example_sce <- runPCA(example_sce, ncomponents=5)

plotReducedDim(example_sce, "PCA", colour_by="Cell_Cycle") +
    scale_color_manual(
        values = c("red", "green", "blue", "black"),
        aesthetics = "fill"
    )
```

![](https://i.imgur.com/q712pfb.png)

``` r


plotReducedDim(example_sce, "PCA", colour_by="Cell_Cycle") +
    scale_color_manual(
        values = c(G1 = "red", S = "green", G0 = "blue", G2M = "black"),
        aesthetics = "fill"
    )
```

![](https://i.imgur.com/gO84N06.png)

**Comment by ilcink** [comment]
I see, the aesthetics="fill" was missing.
Many thanks, @Alanocallaghan !
