### ISSUE TITLE
Cluster order

### ISSUE THREAD

**Issue by ilcink** [alanocallaghan/scater#123]
Hi!

I have a short question about reordering of clusters.
If I want to make a heatmap like

scater::plotHeatmap(sc_data[, order(sc_data$cluster)], features = unique(top10$gene), center = T, zlim = c(-3, 3), colour_columns_by = "cluster", show_colnames = F, cluster_cols = F, cluster_rows=F, fontsize_row = 5, color=rev(viridis::viridis(100, direction = -1)))

and I want the heatmap to show the cluster columns not like 1, 2, 3, 4, 5, but rather 2, 4, 5, 3, 1.

How can I do that?

Thanks!

**Comment by alanocallaghan** [comment]
Can you please post your code as a reproducible example?

**Comment by ilcink** [comment]
So, 
...generating a single-cell experiment object sc_data with several clusters and then

markers_genes <- findMarkers(sc_data, sc_data$cluster, pval.type = "all", direction = "up")
top25 <- lapply(names(markers_genes), function(x) {
  temp <- markers_genes[[x]][1:25, 1:2]
  temp$gene <- rownames(markers_genes[[x]])[1:25]
  temp$cluster <- x
  return(temp)
})
top25 <- as_tibble(do.call(rbind, top25))
top10 <- as_tibble(top25) %>% group_by(cluster) %>% top_n(-10, p.value)
scater::plotHeatmap(sc_data[, order(sc_data$cluster)], features = unique(top10$gene), center = T, zlim = c(-3, 3), colour_columns_by = "cluster", show_colnames = F, cluster_cols = F, cluster_rows=F, fontsize_row = 5, color=rev(viridis::viridis(100, direction = -1)))

@Alanocallaghan , please, let me know, if you need any additional details.

Thank you!

**Comment by LTLA** [comment]
An MRE is usually best if we can just copy and paste the code to see what you see, then we don't have to make up another example to demonstrate that our fix does what you want. You could, for example, use `scater::.mockSCE` to make up an SCE.

@Alanocallaghan It may be as simple as respecting factor level ordering, if `cluster` can be encoded as a factor ahead of time.

**Comment by alanocallaghan** [comment]
Yeah that's what I assume, just not sure if pheatmap respects factor levels already

**Comment by ilcink** [comment]
@LTLA , @Alanocallaghan 

Ok, so, for example

```r
library("scran")
library("scater")
library("magrittr")
library("tibble")
library("dplyr")
set.seed(10000)
sce <- mockSCE()
sce
sce <- scater::logNormCounts(sce)
gene_variancs <- scran::modelGeneVar(sce)
top_hvgs <- scran::getTopHVGs(gene_variancs, prop = 0.5)
length(top_hvgs)
sce <- scater::runPCA(sce, subset_row = top_hvgs, ncomponents = 10)
neighbour_graph <- scran::buildSNNGraph(sce, k = 10, use.dimred = "PCA")
cluster_membership <- igraph::cluster_walktrap(neighbour_graph)$membership
sce$cluster <- factor(cluster_membership)
sce <- scater::runTSNE(sce, dimred = "PCA", perplexity = 5, name = "TSNE_5")
scater::plotReducedDim(sce, "TSNE_5")
sce$cluster
markers_genes <- findMarkers(sce, sce$cluster, pval.type = "all", direction = "up")
top25 <- lapply(names(markers_genes), function(x) {
  temp <- markers_genes[[x]][1:25, 1:2]
  temp$gene <- rownames(markers_genes[[x]])[1:25]
  temp$cluster <- x
  return(temp)
})
top25 <- as_tibble(do.call(rbind, top25))
top10 <- as_tibble(top25) %>% group_by(cluster) %>% top_n(-10, p.value)
scater::plotHeatmap(sce[, order(sce$cluster)], features = unique(top10$gene), center = T, zlim = c(-3, 3), colour_columns_by = "cluster", show_colnames = F, cluster_cols = F, cluster_rows=F, fontsize_row = 5, color=rev(viridis::viridis(100, direction = -1)))
```
It generates a heatmap with columns of clusters 1,  2,  3.
How can I make them in the order of  2, 3, 1 for example?

**Comment by alanocallaghan** [comment]
You can just change the levels of the cluster factor, eg `sce$cluster <- factor(sce$cluster, levels = c(2, 3, 1))` or [use a package to do the same thing](https://forcats.tidyverse.org/reference/fct_reorder.html)

**Comment by ilcink** [comment]
@Alanocallaghan Thanks!!

**Comment by LTLA** [comment]
We should probably mention this trick in the documentation, if it's not obvious from `?pheatmap`.

**Comment by alanocallaghan** [comment]
This isn't a scater or pheatmap trick in particular, just changing the ordering defined by `sce[, order(sce$cluster)]`

**Comment by LTLA** [comment]
Oh, I thought they were using `order_columns_by="cluster"`. I guess not.
