### ISSUE TITLE
Confused about outlier detection with runColDataPCA

### ISSUE THREAD

**Issue by dweemx** [alanocallaghan/scater#124]
Hi, 
From the documentation of `runColDataPCA`, it is stated that outliers (`outliers=TRUE`) are detected based on PCA coordinates.
However when I look at the implementation of this function it seems that outlier detection is performed on the `colData` and not on the PCA coordinates. Is the documentation out of sync ? Or am I missing something ?

**Comment by alanocallaghan** [comment]
Seems that way yeah

**Comment by alanocallaghan** [comment]
Could make some sort of tenuous point about PCA being a rotation of the original coordinates so technically this is not totally incorrect, but that seems a bit dishonest. 

I think running it on the original data is fine but the documentation should definitely reflect what the code does

**Comment by LTLA** [comment]
The `outliers=TRUE` was a real headache. We used another package for outlier detection at first - can't remember its name - but we switched because that package added a bunch of system dependencies that made it impossible to install. I must have gotten confused when rewriting it for **robustbase**.

**Comment by alanocallaghan** [comment]
Do you reckon it's better to revert to working on PCA coords then?

**Comment by LTLA** [comment]
Yeah, probably. Don't think it makes all that much of a difference.
