### ISSUE TITLE
Transfer iSEEu's AggregatedDotPlot settings to plotDots

### ISSUE THREAD

**Issue by LTLA** [alanocallaghan/scater#129]
**iSEEu**'s `AggregatedDotPlot` class has a few settings that we should probably transfer to the `plotDots` class, mostly with respect to modifying the color scheme, centering and scaling, etc.

**Comment by alanocallaghan** [comment]
https://github.com/Alanocallaghan/scater/tree/isee-options but i need to check if there's more options to copy over

**Comment by alanocallaghan** [comment]
We good here or are there any extras?

**Comment by LTLA** [comment]
I think we're good. I honestly don't remember the status, but I didn't complain at the time.
