### ISSUE TITLE
Local density information

### ISSUE THREAD

**Issue by alanocallaghan** [alanocallaghan/scater#132]
Would be nice to have a way to visualise density in cellwise plots, eg ggpointdensity or ggmarginal

**Comment by mdmanurung** [comment]
Are you interested in a PR for this? And also how about giving an option to use scattermore as backend for scatterplot for faster results?

**Comment by alanocallaghan** [comment]
First step would be to generate some example outputs so we can consider implementation details, but in principal yes

Scattermore support would be good yeah, that should be a bit more straightforward

**Comment by alanocallaghan** [comment]
re: scattermore, see https://github.com/Alanocallaghan/scater/issues/173

**Comment by alanocallaghan** [comment]
Partially addressed by 0823d056b7191a8d71e29c2eedcf633f26112c9f; ggmarginal should always work

**Comment by alanocallaghan** [comment]
#191 probably
