### ISSUE TITLE
Error in perplexity calculation in runTSNE

### ISSUE THREAD

**Issue by ycl6** [alanocallaghan/scater#135]
The perplexity should be scales with the number of cells, however the `nrow` function used in the [perplexity calculation](https://github.com/Alanocallaghan/scater/blob/0fa968507944d724963f9a14b50eface25b2dccb/R/runTSNE.R#L89) will get the total number of genes instead of cells.

```R
    if (is.null(perplexity)) {
        perplexity <- min(50, floor(nrow(x) / 5))
    }
```

**Comment by LTLA** [comment]
https://github.com/Alanocallaghan/scater/blob/d4b3c22d2ca2d1566444379712ae9c6ec88f8459/R/runTSNE.R#L83-L85

should transpose the matrix so that the rows are cells.

**Comment by ycl6** [comment]
Thanks @LTLA, you are right. 
When the input is a matrix, the default setting of `dimred=NULL` will trigger the transpose of the matrix so that rows are cells.

https://github.com/Alanocallaghan/scater/blob/d4b3c22d2ca2d1566444379712ae9c6ec88f8459/R/runTSNE.R#L124-L129

I'll close this issue.
