### ISSUE TITLE
Include a snifter option in runTSNE?

### ISSUE THREAD

**Issue by LTLA** [alanocallaghan/scater#136]
We could add it to `Suggests:` so that we can just flip a switch to use it.

BTW we should probably promote **Rtsne** to an `Imports`.

**Comment by alanocallaghan** [comment]
Sounds good on both. been meaning to do this, didn't have time to cram it in last release

**Comment by alanocallaghan** [comment]
23b6970573cc95066dcf4315f6b11b827e74bd5a
