### ISSUE TITLE
Why is scale = FALSE for runPCA function calls in scater vignette?

### ISSUE THREAD

**Issue by zhewa** [alanocallaghan/scater#139]
Hi,

The default setting is `scale = FALSE` in `runPCA`. In the _4.1 Principal components analysis section_ of the vignette of scater on Bioconductor, why is it `example_sce <- runPCA(example_sce)` and not `example_sce <- runPCA(example_sce, scale = TRUE)`? Is it recommended to set `scale = FALSE` for `runPCA` when using `scater` to analyze scRNA-seq datasets?

**Comment by alanocallaghan** [comment]
If you scale features then they each have equal weighting in PCA; this may be desirable sometimes but as a general use case I don't think it's appropriate to give equal weight to genes with large variability in expression and genes with extremely small variability in expression in the population under study.

Yes I would usually recommend against scaling when performing PCA.

As usual Aaron Lun's written some useful stuff on the topic, eg https://ltla.github.io/SingleCellThoughts/general/standardization.html
