### ISSUE TITLE
could not run plotGroupedHeatmap.R

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [alanocallaghan/scater#142]
Hi,

Thank you for this great package and plotGroupedHeatmap.R script.
I tried to run plotGroupedHeatmap.R, but it seems this function has lots of dependencies. I tried to trace and install all dependencies though, I still stuck in " could not find function "DummyArrayGrid" "

It seems scater package does not have plotGroupedHeatmap() function.  Do you have any recommendation to run plotGroupedHeatmap.R?

Thank you for your help!
Best,
Xiaofei

**Comment by alanocallaghan** [comment]
What happens if you try to run the example from `help("plotGroupedHeatmap")`?

The output should be something like this:

``` r
library("scater")
example_sce <- mockSCE()
example_sce <- logNormCounts(example_sce)
example_sce$Group <- paste0(example_sce$Treatment, "+", example_sce$Mutation_Status)
plotGroupedHeatmap(example_sce, features=rownames(example_sce)[1:10],
         group="Group")
```

![](https://i.imgur.com/fkG7uQm.png)

**Comment by XiaofeiSunUCSF** [comment]
I restarted my laptop and this time works :)! Sorry to bother you. I will close this one. 
Thank you for your quick response! 
Xiaofei

**Comment by LTLA** [comment]
For future reference: if you load a package, and then install a new version of the same package, you need to restart R if you want the update to take effect. The update won't displace the already-loaded version of the package in a running R session.

**Comment by XiaofeiSunUCSF** [comment]
Thank you so much for your tips 👍 👍 👍 👍
