### ISSUE TITLE
Custom centering and scaling options for runPCA?

### ISSUE THREAD

**Issue by ColeWunderlich** [alanocallaghan/scater#151]
Hello,

I would like to perform custom scaling and centering when performing PCA on an sce object.  

My goal is to mean center and standard deviation scale each row (gene). 
Ie: `gene_i = (gene_i - mean(gene))/sd(gene)`

For runPCA `scale=T` appears to at least accomplish the scaling I want to do (by setting the variance to unity), but there does not appear to be a `center` parameter.  

I know the BiocSingular runPCA has a `center` parameter, but it is column based rather than row based, which to me implies the count matrix is getting transposed at some point.  I also believe the BiocSignular `center` default is to center by column sum rather than mean.

Is there any way to provide a custom center parameter/vector?  I suppose one option would be to pre-transform the count matrix, but then you would lose out on the speedup due to sparsity (or the block processing mentioned in the BiocSingular options documentation).

**Comment by alanocallaghan** [comment]
`center=TRUE` is the default in BiocSingular so unless I'm misunderstanding something this is a solved problem. You could check this by doing something like the following and seeing if it matches what you get just by running `runPCA(sce, scale=TRUE)`

```r
library(scater)
library(BiocSingular)
sce <- mockSCE()
mat <- counts(sce)
smat <- scale(t(mat), center=TRUE)
pc <- runPCA(smat, rank=10)
reducedDim(sce, "scaledPCA") <- pc$x
```

**Comment by ColeWunderlich** [comment]
If you look at page 2 here: https://bioconductor.org/packages/release/bioc/manuals/BiocSingular/man/BiocSingular.pdf

" If center=TRUE, C is defined as the *column sums* of x. If center=NULL or FALSE, all elements
of C are set to zero. If center is a numeric vector with length equal to ncol(x), it is used to
directly define C." 
(emphasis mine) 

I would like to center by the column means instead of the sums (technically the row means before transposition). However I'm not sure how to do so given that `center` is not an exposed parameter and .calculate_PCA does not pass `center` to the underlying run_PCA call. 
https://github.com/Alanocallaghan/scater/blob/092703b2bd3dca6d97ca85b5dbe887a661388281/R/runPCA.R#L137

**Comment by alanocallaghan** [comment]
I would suggest you check whether that is actually what BiocSingular does because I don't believe that it is, and I don't think "subtract column sums" is a common interpretation of "centering a vector" 

https://github.com/LTLA/BiocSingular/blob/54d4bc9894377e148edcb3a9d1107390967cff87/R/standardize_matrix.R#L37

**Comment by LTLA** [comment]
Oops. That piece of documentation should probably say "column means".

The functionality is correct, though.

**Comment by ColeWunderlich** [comment]
Thanks guys!  Centering by mean makes a lot more sense to me. 

I don't think centering is turned on by default though.  On my setup the default `bsparam` is `FastAutoParam` which I believe usually calls `irlba`.  Looking at the `runIrlbaSVD` function signature it appears that centering and scaling are off by default.

```
runIrlbaSVD(x, k=5, nu=k, nv=k, center=FALSE, scale=FALSE, deferred=FALSE,
         extra.work=7, ..., fold=Inf, BPPARAM=SerialParam())
```
([page 9 here](https://bioconductor.org/packages/release/bioc/manuals/BiocSingular/man/BiocSingular.pdf))

--------
I'm also curious why scaling is done before input to the various PCA algorithms since the manual mentions it is preferred to do deferred/'in-place'  scaling via the `scale` and `center` parameters.  It appears, however, that scaling is done before input to `runPCA`. 

https://github.com/Alanocallaghan/scater/blob/207e91e80f42690394a450c2a908d082b4ca74bb/R/utils_reddim.R#L48-L52

This would preserve sparsity though (I think) so maybe it doesn't matter.   Sorry for the extra question, I'm new to this and trying to understand best practices.

**Comment by ColeWunderlich** [comment]
Also @Alanocallaghan thanks for the example code!  I didn't know about `mockSCE` but that seems very useful.  I will give your example code a try.

**Comment by ColeWunderlich** [comment]
### EDIT
Sorry, I just realized that the `BiocSingular runPCA` has centering on by default.  I'm assuming that's what is being called here since the input `x` is a matrix? 
https://github.com/Alanocallaghan/scater/blob/092703b2bd3dca6d97ca85b5dbe887a661388281/R/runPCA.R#L137
```
runPCA              package:BiocSingular               R Documentation
.....
Usage:

     runPCA(x, ...)
     
     ## S4 method for signature 'ANY'
     runPCA(x, rank, center=TRUE, scale=FALSE, get.rotation=TRUE,
         get.pcs=TRUE, ...) 
```

**Comment by alanocallaghan** [comment]
I believe so based on my own trace through the stack, but I'm sure Aaron would be delighted to inform me if we're wrong there

**Comment by ColeWunderlich** [comment]
### Update

I'm not sure if I am just doing something wrong, or if there is a real issue here, but I cannot get the test @Alanocallaghan recommended to come out matching.  For some reason the PCA results are very different between a manually pre-processed matrix and using the scater functions.

```Python
library(scater)
library(BiocSingular)
library(matrixStats)

msce = mockSCE()
trData = scale(t(counts(msce)), center=T) 

#--Sanity-Check--#
modData = sweep(counts(msce),1,rowMeans(counts(msce)),"-")
modData = sweep(modData,1,rowSds(modData),"/")
all.equal(t(trData)[,],modData)
## [1] TRUE
#--END--#

truePCA = runPCA(trData, rank=10, center=F, scale=F)

testPCA = runPCA(msce,scale=T,exprs_values="counts",ncomp=10)

all.equal(reducedDim(testPCA,"PCA")[,], truePCA$x)
## [1] "Mean relative difference: 1.96072"

reducedDim(testPCA,"PCA")[1:3,]
##                PC1        PC2       PC3        PC4       PC5        PC6
##Cell_001  3.5387462 -1.1704494 -3.072264  0.4524418 0.2197115 -0.4791506
##Cell_002 -4.0005218 -2.1299038 -3.137201 -0.1801237 1.1784164 -2.3427737
##Cell_003 -0.3014688  0.7582901  2.166544  2.7471664 4.2308546  3.8147991
##                 PC7        PC8        PC9      PC10
##Cell_001  0.26379138  1.0361218 -3.8022340 -1.492945
##Cell_002 -0.05308909  5.1674820 -0.5749177 -1.679414
##Cell_003  0.28729004 -0.7360297 -1.4173014 -1.441428

truePCA$x[1:3,]
##               PC1       PC2        PC3        PC4        PC5        PC6
##Cell_001 0.6736703 -1.649140  1.3326437 -6.6029282  2.5093180 -3.0775640
##Cell_002 1.0531913 -5.324722 -1.1514131 -5.8866585 -1.5083107  2.9212274
##Cell_003 0.9714008  3.808349 -0.5225248  0.5065259 -0.4507646 -0.9469541
##                PC7        PC8        PC9        PC10
##Cell_001  2.1586882 -3.2610878  0.8851745  -0.8637694
##Cell_002 -2.3570903 -0.6730905 -2.6289330 -10.7964382
##Cell_003 -0.2064027  4.7424629 -0.4666574   0.9645415

#Note: Differences not attributable to filtering out zero variances, all are above the threshold
sum(rowVars(counts(msce)) < 1e-8)
## [1] 0

##Scale only or center only?
#No
assay(msce, "centeredCounts") = sweep(counts(msce),1,rowMeans(counts(msce)),"-")
all.equal(reducedDim(runPCA(msce,scale=T,exprs_values="centeredCounts",ncomp=10),"PCA")[,], truePCA$x)
## [1] "Mean relative difference: 1.876548"

#Also no
assay(msce, "scaledCounts") = sweep(counts(msce),1,rowSds(counts(msce)),"/")
all.equal(reducedDim(runPCA(msce,scale=T,exprs_values="scaledCounts",ncomp=10),"PCA")[,], truePCA$x)
## [1] "Mean relative difference: 1.991491"
```

**Comment by LTLA** [comment]
There's a couple of points here.

As you've realized, the SVD default is `center=FALSE`. This is because the SVD is closely related to _but is not_ a PCA. You can do an SVD on a matrix outside of PCA (e.g., for rank discovery, see `Matrix::rankMatrix`) - there's no reason to believe that the user wants to center it beforehand.

The second point is that `scater::runPCA` does a bit more work than `BiocSingular::runPCA`. In particular:

- `scater::runPCA()` only uses the top 500 HVGs, while `BiocSingular::runPCA()` doesn't do any filtering.
- `scater::runPCA()` uses IRLBA by default, while `BiocSingular::runPCA()` uses the exact SVD by default.

This is a rather unfortunate consequence of `runPCA()` being the obvious name for the function in both packages. While **scater**'s defaults are adjusted for single-cell work, **BiocSingular**'s defaults are designed for the most general use case, resulting in the observed discrepancy when the defaults are used. If we force the parameters to be the same:

```r
library(scater)
library(BiocSingular)
library(matrixStats)

msce = mockSCE()
trData = scale(t(counts(msce)), center=T) 

# Implicitly calls the ANY method from BiocSingular
truePCA = runPCA(trData, rank=10, center=F, scale=F)

# Implicitly calls the SingleCellExperiment method from scater
testPCA = runPCA(msce,scale=T,exprs_values="counts",ncomp=10, ntop=Inf, BSPARAM=ExactParam())

truePCA$x[1:10,]
##                 PC1        PC2        PC3          PC4        PC5        PC6
## Cell_001 -1.3631284  5.0756191 -5.6451251   0.94134847 -0.6081867  1.4735192
## Cell_002  2.5576637 -1.9314257 -4.7839781   2.23587688  1.6758286  1.1268065
## Cell_003 -0.3880852 -1.6174310  3.9178061  -5.74248132 -3.5485162 -3.0777840
## Cell_004  3.1999186 10.1211569  0.5769412  -3.36363548  8.2095244 11.8402442
## Cell_005 -1.8308305 -0.7682956  4.1177977  -2.36814303  1.1579677 -3.8451692
## Cell_006 -0.7201888 -2.1422028 -8.6948596 -12.44629180 -3.2253276 -0.5154447
## Cell_007  2.8221437  5.4789644  2.8272247   1.93929241 -2.2990983  5.8337883
## Cell_008 -0.1744646 -5.3754545 -2.4873648  -0.04622198 -3.4154538 -4.8283688
## Cell_009  0.7681552  6.2054545  2.5099379  -3.76820390 -0.1014846  2.6455650
## Cell_010  0.3460579  5.2249745  2.4821685   0.41712575 -4.1577395  3.6400455
##                 PC7        PC8        PC9       PC10
## Cell_001 -2.5285248 -1.1290267  2.4014078 -2.8845134
## Cell_002  5.0306541  3.6469920  2.2052500 -0.7578338
## Cell_003 -2.3968271 -6.5541571 -0.4929776  0.3383554
## Cell_004  0.3772971 -6.6672881  7.6673691  6.5845104
## Cell_005 -4.3704051  2.1987985 -1.1815347  0.9948988
## Cell_006 -3.6085043 -0.7906928  1.6607405  2.9198967
## Cell_007 -2.4187318 -0.3925718 -1.6755010  0.7207772
## Cell_008  3.2089096 -3.9073616  5.1567712 -3.4209855
## Cell_009 -1.0042918  1.0263714  4.6623676  1.2470028
## Cell_010  1.9053218  1.4587264 10.0927352  1.4675147

reducedDim(testPCA)[1:10,]
##                 PC1        PC2        PC3          PC4        PC5        PC6
## Cell_001 -1.3631284  5.0756191 -5.6451251   0.94134847 -0.6081867  1.4735192
## Cell_002  2.5576637 -1.9314257 -4.7839781   2.23587688  1.6758286  1.1268065
## Cell_003 -0.3880852 -1.6174310  3.9178061  -5.74248132 -3.5485162 -3.0777840
## Cell_004  3.1999186 10.1211569  0.5769412  -3.36363548  8.2095244 11.8402442
## Cell_005 -1.8308305 -0.7682956  4.1177977  -2.36814303  1.1579677 -3.8451692
## Cell_006 -0.7201888 -2.1422028 -8.6948596 -12.44629180 -3.2253276 -0.5154447
## Cell_007  2.8221437  5.4789644  2.8272247   1.93929241 -2.2990983  5.8337883
## Cell_008 -0.1744646 -5.3754545 -2.4873648  -0.04622198 -3.4154538 -4.8283688
## Cell_009  0.7681552  6.2054545  2.5099379  -3.76820390 -0.1014846  2.6455650
## Cell_010  0.3460579  5.2249745  2.4821685   0.41712575 -4.1577395  3.6400455
##                 PC7        PC8        PC9       PC10
## Cell_001 -2.5285248 -1.1290267  2.4014078 -2.8845134
## Cell_002  5.0306541  3.6469920  2.2052500 -0.7578338
## Cell_003 -2.3968271 -6.5541571 -0.4929776  0.3383554
## Cell_004  0.3772971 -6.6672881  7.6673691  6.5845104
## Cell_005 -4.3704051  2.1987985 -1.1815347  0.9948988
## Cell_006 -3.6085043 -0.7906928  1.6607405  2.9198967
## Cell_007 -2.4187318 -0.3925718 -1.6755010  0.7207772
## Cell_008  3.2089096 -3.9073616  5.1567712 -3.4209855
## Cell_009 -1.0042918  1.0263714  4.6623676  1.2470028
## Cell_010  1.9053218  1.4587264 10.0927352  1.4675147
```

The differences in defaults are confusing but there wasn't much of a better solution if we wanted to use the same function name. It's hard to imagine what else to call this function - **BiocSingular** already had `runSVD`, and **scater** had `runTSNE`, `runUMAP`, etc., so the collision at `runPCA` was kind of inevitable. And hey, at least it does the "right" thing for casual users.

**Comment by alanocallaghan** [comment]
fwiw I don't think it's strange that `runPCA` methods for different objects would have different defaults even within the same package. Although I think exposing more of the BiocSingular options in scater isn't a terrible idea
