### ISSUE TITLE
How to put show_smooth line in front of the points.

### ISSUE THREAD

**Issue by NaomiCroft** [alanocallaghan/scater#155]
Hi, the data points are obscuring the show-smooth line, as seen below
![image](https://user-images.githubusercontent.com/48726315/127865220-40a73fa4-8ffa-434b-a9f8-0dff98631b47.png)

If I just change the transparency of the points then the colour changes which then means the points don't match the colour scheme in the rest of my plots:
![image](https://user-images.githubusercontent.com/48726315/127865322-2196d9a8-37d2-4e47-8e29-279c4b8969bc.png)

Is there a way to bring the line to the front if the points?

Here is my current script:

palette <- c("#7CAE00", "#00BE67", "#F8766D", "#00BFC4", "#C77CFF", "#00A9FF", "#FF61CC")
colData(sce_tcell)$cluster_colour <- palette[sce_tcell$ident]

plotExpression(sce_tcell, features = "sh2d1a", x = "slingPseudotime_1", colour = "ident", show_smooth = T) + geom_point(colour = colData(sce_tcell)$cluster_colour, size = 1) + theme(legend.position = "none") 

Thanks for your time!

**Comment by alanocallaghan** [comment]
Why are you adding a geom_point layer?

**Comment by NaomiCroft** [comment]
Ah I see what you mean. I think I added it in in order to try and change the transparency and size of the points

**Comment by alanocallaghan** [comment]
I see why. You're trying to change the colour palette. A better way to do that would be

```r
palette <- c(
    celltype1 = "#7CAE00",
    celltype2 = "#00BE67",
    celltype3 = "#F8766D", 
    celltype4 = "#00BFC4",
    celltype5 = "#C77CFF",
    celltype6 = "#00A9FF",
    celltype7 = "#FF61CC"
)

plotExpression(sce, colour = "ident", show_smooth = TRUE) + scale_colour_manual(values = palette)
```

**Comment by NaomiCroft** [comment]
plotExpression(sce_tcell, features = "LOC115543843", x = "slingPseudotime_3", colour = "ident", show_smooth = T) + theme(legend.position = "none") 

![image](https://user-images.githubusercontent.com/48726315/127868610-00ed2719-24ef-4574-b077-83168f26ad4d.png)

If I remove that then the transparency increases again which changes the colours to something which is not correct

**Comment by NaomiCroft** [comment]
If I enter what you suggest:
palette <- c(
    celltype1 = "#7CAE00",
    celltype2 = "#00BE67",
    celltype3 = "#F8766D", 
    celltype4 = "#00BFC4",
    celltype5 = "#C77CFF",
    celltype6 = "#00A9FF",
    celltype7 = "#FF61CC"
)

plotExpression(sce_tcell, features = "LOC115543843", colour = "ident", show_smooth = TRUE) + scale_colour_manual(values = palette)

![image](https://user-images.githubusercontent.com/48726315/127868916-db2d8dd2-6204-4043-83c9-07a39a1f96d4.png)

**Comment by NaomiCroft** [comment]
Ah I have missed the x-axis:
palette <- c(
    celltype1 = "#7CAE00",
    celltype2 = "#00BE67",
    celltype3 = "#F8766D", 
    celltype4 = "#00BFC4",
    celltype5 = "#C77CFF",
    celltype6 = "#00A9FF",
    celltype7 = "#FF61CC"
)

plotExpression(sce_tcell, features = "LOC115543843", x = "slingPseudotime_3", colour = "ident", show_smooth = TRUE) + scale_colour_manual(values = palette)

![image](https://user-images.githubusercontent.com/48726315/127869113-9e957f3a-ef91-4f4a-9141-2707346dd638.png)


Now there is no points

**Comment by alanocallaghan** [comment]
The code I gave was an example. I can't reproduce the plots you're showing because your code is not a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example). You should replace `celltype1` (etc) with the actual `ident`values in your data (0-6 I guess, I didn't know that because I couldn't reproduce your code)

**Comment by NaomiCroft** [comment]
Ok thank you, I see. But would this solve the original problem with the line being buried by the points?

**Comment by alanocallaghan** [comment]
yes. the reason the points were behind the lines is that ggplot2 adds geoms to plots in the same order they are added in the code. Therefore you had a geom_point layer (created by scater), then a geom_smooth layer (the smooth line), then the geom_point layer that you added after calling plotExpression

**Comment by alanocallaghan** [comment]
I don't remember how scale_colour_manual works with unnamed vectors in value (probably based on factor levels) but you may be able to just do

```r
palette <- c("#7CAE00", "#00BE67", "#F8766D", "#00BFC4", "#C77CFF", "#00A9FF", "#FF61CC")
plotExpression(sce, [other arguments]) + scale_colour_manual(values = palette)
```

**Comment by NaomiCroft** [comment]
Yes that works! Brilliant, thank you
