### ISSUE TITLE
problem with `calculateTSNE` with `use_fitsne=TRUE` and `dimred="PCA"`

### ISSUE THREAD

**Issue by julien-roux** [alanocallaghan/scater#156]
When using `runTSNE()` or `calculateTSNE()` with `use_fitsne=TRUE`, setting up `dimred="PCA"` leads the argument `pca` to be set to `FALSE` which is then passed on to `snifter::fitsne` and leads to an error:
```
Error in (function (x, simplified = FALSE, n_components = 2L, n_jobs = 1L,  : 
  unused argument (pca = FALSE)
```

See line 109 in https://github.com/Alanocallaghan/scater/blob/master/R/runTSNE.R. The argument `pca` is set to `NULL` only if it was originally `TRUE`, I think the fix is to move this line of code out of the `if` statement.

Additional question: if a dimred is provided as input and we do not want `snifter::fitsne` to run a PCA initialization step, should the `initialization` parameter of `snifter::fitsne` be set to `random`?

**Comment by alanocallaghan** [comment]
`pca` doesn't control initialization as far as I know

https://github.com/jkrijthe/Rtsne/blob/14b195fe09a1cbc2b787d3ee74d0b0bbe066f2e6/R/Rtsne.R#L154

**Comment by julien-roux** [comment]
With `Rtsne` the behavior is fine. The issue is with `use_fitsne=TRUE` which makes the function use `snifter::fitsne()`. As it has no `pca` argument, this is turned to an `initialization` argument if it was set to TRUE, and creates problems if it was FALSE...

Indeed I am not sure that `pca=TRUE` should be translated to `initilization="pca"`, but this is another issue maybe

**Comment by alanocallaghan** [comment]
Yes, I understand the issue and am currently fixing it.

**Comment by alanocallaghan** [comment]
Off topic but [the link on your github profile is dead](https://biomedizin.unibas.ch/services/bioinformatics-core-facility/)

**Comment by julien-roux** [comment]
> Off topic but [the link on your github profile is dead](https://biomedizin.unibas.ch/services/bioinformatics-core-facility/)

Oh thanks for letting me know, I've just fixed this

**Comment by alanocallaghan** [comment]
No worries - I was just curious :) 

thanks for flagging the issue

**Comment by alanocallaghan** [comment]
If you `devtools::install_github("Alanocallaghan/snifter"); devtools::install_github("Alanocallaghan/scater")` it should be fixed

**Comment by alanocallaghan** [comment]
I'm gonna assume that did it but please let me know if not!
