### ISSUE TITLE
remove destiny?

### ISSUE THREAD

**Issue by alanocallaghan** [alanocallaghan/scater#157]
I am really quite sick of checks failing locally or on remote because destiny has fallen out of favour

**Comment by alanocallaghan** [comment]
Not pushed to bioc yet but probably deprecating it adb3463b5e22aba583517f903de4836745d01a18

**Comment by LTLA** [comment]
Yes, this has been a bugbear for some time.

**Comment by PeteHaitch** [comment]
@Alanocallaghan: Is it possible to push https://github.com/Alanocallaghan/scater/commit/adb3463b5e22aba583517f903de4836745d01a18 to BioC?
**destiny** has [now been deprecated](https://bioconductor.org/packages/release/bioc/html/destiny.html) and is no longer available in BioC 3.15 (https://bioconductor.org/packages/devel/bioc/html/destiny.html returns 'page not found').
I think this is currently blocking **scater** from being available on BioC 3.15 (https://bioconductor.org/checkResults/3.15/bioc-LATEST/scater/)

**Comment by alanocallaghan** [comment]
That's been pushed already, I just have to go one better and `.Defunct` it apparently.

Should be removed for next build, will keep my eye on the build report and close this if so
