### ISSUE TITLE
plotHighestExprs

### ISSUE THREAD

**Issue by davismcc** [alanocallaghan/scater#16]
_From @weizhiting on May 22, 2017 15:51_

![rplot](https://cloud.githubusercontent.com/assets/24773527/26317057/2d8384d8-3f51-11e7-802a-eb2c596317b6.png)
Hi,when i use this command,plotHighestExprs(example_sceset,exprs_values = 'exprs'),
i get the attached png,but seems the circle in the png is not at the right position?Thanks!

_Copied from original issue: davismcc/archive-scater#113_

**Comment by LTLA** [comment]
Seems to work fine in the Github version with:

```r
example(plotHighestExprs)
example_sce <- normalize(example_sce)
plotHighestExprs(example_sce,exprs_values = 'logcounts')
```
