### ISSUE TITLE
label by ggrepel not centred in plotReducedDim 

### ISSUE THREAD

**Issue by ycl6** [alanocallaghan/scater#162]
Hi,

Regarding the second comment in https://github.com/Alanocallaghan/scater/issues/152#issuecomment-889993137, I recently updated to the latest version and found all the labels are not centred anymore. I found this has made it difficult to associated the labels to the corresponding clusters as each label move in random directions (up, down. left, right) from the centre. I would much appreciate if the _tweak_ mentioned in the comment can be implemented, or give user the option to pass additional args to `geom_text_repel`.

**Comment by alanocallaghan** [comment]
Can you provide a short reproducible example where this is an issue?

**Comment by ycl6** [comment]
Hi @Alanocallaghan 

Here I use the `PaulHSCData` and the workflow from OSCA to demonstrate. Cluster labels were offsetted in various directions from the centre, and several labels were positioned not at an _ideal_ position (I understand aesthetic is pretty much a personal preference, but  :wink: ).

If the labels weren't overlapping as described in #152 , centering actually works very well most of the times.  

```R
library(scRNAseq)
sce.paul <- PaulHSCData(ensembl=TRUE)

library(AnnotationHub)
ens.mm.v97 <- AnnotationHub()[["AH73905"]]
anno <- select(ens.mm.v97, keys=rownames(sce.paul), keytype="GENEID", columns=c("SYMBOL", "SEQNAME"))
rowData(sce.paul) <- anno[match(rownames(sce.paul), anno$GENEID),]

unfiltered <- sce.paul

library(scater)
stats <- perCellQCMetrics(sce.paul)
qc <- quickPerCellQC(stats, batch=sce.paul$Plate_ID)

# Detecting batches with unusually low threshold values.
lib.thresholds <- attr(qc$low_lib_size, "thresholds")["lower",]
nfeat.thresholds <- attr(qc$low_n_features, "thresholds")["lower",]
ignore <- union(names(lib.thresholds)[lib.thresholds < 100], names(nfeat.thresholds)[nfeat.thresholds < 100])

# Repeating the QC using only the "high-quality" batches.
qc2 <- quickPerCellQC(stats, batch=sce.paul$Plate_ID, subset=!sce.paul$Plate_ID %in% ignore)
sce.paul <- sce.paul[,!qc2$discard]

colData(unfiltered) <- cbind(colData(unfiltered), stats)
unfiltered$discard <- qc2$discard
unfiltered$Plate_ID <- factor(unfiltered$Plate_ID)

library(scran)
set.seed(101000110)
clusters <- quickCluster(sce.paul)
sce.paul <- computeSumFactors(sce.paul, clusters=clusters)
sce.paul <- logNormCounts(sce.paul)

set.seed(00010101)
dec.paul <- modelGeneVarByPoisson(sce.paul)
top.paul <- getTopHVGs(dec.paul, prop=0.1)

set.seed(101010011)
sce.paul <- denoisePCA(sce.paul, technical=dec.paul, subset.row=top.paul)
sce.paul <- runTSNE(sce.paul, dimred="PCA")

snn.gr <- buildSNNGraph(sce.paul, use.dimred="PCA", type="jaccard")
colLabels(sce.paul) <- factor(igraph::cluster_louvain(snn.gr)$membership)
```

With label centred
![Label centred](https://user-images.githubusercontent.com/9032946/152253021-5165d264-646e-4fe3-8455-6c3f07bb0e1d.png)

Label offset from centre by `geom_text_repel`
![Label not centred](https://user-images.githubusercontent.com/9032946/152253031-e8552c40-afbf-4bb3-8915-d5edd6ee6e2e.png)

**Comment by alanocallaghan** [comment]
Thanks

**Comment by ycl6** [comment]
@Alanocallaghan Thanks!

**Comment by alanocallaghan** [comment]
From #164:

> I tried the latest version and unfortunately the _tweak_ mentioned in https://github.com/slowkow/ggrepel/issues/180 doesn't resolve the issue raised in #162 and https://github.com/Alanocallaghan/scater/issues/152#issuecomment-889993137. I also found related issues raised in `ggrepel`'s repo.

> But, I am able to confirm `force = 0` will disable the repel functionality. I put together a quick function to test this by adapting the codes from `plotReducedDim`. By default, `force = 1`, with `force = 0` the labels will be positioned directly over the given coordinates.

> force - Force of repulsion between overlapping text labels. Defaults to 1.


```R
add_label <- function(object, dimred, text_by = "label", text_size = 5, text_colour = "black") {
    text_out <- retrieveCellInfo(object, text_by, search = "colData")
    text_out$val <- as.factor(text_out$val)
    red_dim <- as.matrix(reducedDim(object, dimred))
    df_to_plot <- data.frame(red_dim[, seq_len(2), drop = FALSE])
    colnames(df_to_plot)[seq_len(2)] <- c("X", "Y")
    by_text_x <- vapply(split(df_to_plot$X, text_out$val), median, FUN.VALUE = 0)
    by_text_y <- vapply(split(df_to_plot$Y, text_out$val), median, FUN.VALUE = 0)

    ggrepel::geom_text_repel(data = data.frame(x = by_text_x, y = by_text_y, label = names(by_text_x)),
                             mapping = aes(x = x, y = y, label = label),
                             inherit.aes = FALSE, size = text_size, colour = text_colour, force = 0)
}

plotReducedDim(sce.paul, "TSNE", colour_by = "label") + add_label(sce.paul, "TSNE")
```

> Below is the code I use to plot. It produces the same plot as before with the text repelled away from centre. 
Looking at the suggestion in https://github.com/slowkow/ggrepel/issues/180#issuecomment-755411911, I also tried `point.size = NA` but that didn't work either.

```R
set.seed(0123210)
plotReducedDim(sce.paul, "TSNE", colour_by = "label", text_by = "label", text_size = 7, theme_size = 16)
```

```
scater_1.23.4
ggrepel_0.9.1
```
