### ISSUE TITLE
Issue with runTSNE and deprecated parameter, i.e. use_dimred?

### ISSUE THREAD

**Issue by gabrielet** [alanocallaghan/scater#163]
This is not actually a question but rather an issue I found out which [I posted on another website](https://bioinformatics.stackexchange.com/questions/18462/is-use-dimred-deprecated-or-is-this-a-runtsne-bug).

Briefly, the problem arise when using `runTSNE` and the deprecated parameter `use_dimred`. Indeed, it is still possible to use the parameter, for the reason explained in the link I provided, `use_dimred`. It is definitely likely that someone using a not-so-old pipeline might still be using such parameter without any warning or error thrown by the running code. Problem is, its use is misleading and will surely lead to wrong conclusions once the generated tSNE is used to decide how to proceed with downstream analyses.

I would suggest to add a warning or something to point out that with the newest versions of the package, the use of `use_dimred` is deprecated while 'dimred` must be used instead.

**Comment by alanocallaghan** [comment]
Added a warning that I may end up removing in later versions
