### ISSUE TITLE
Centering labels in plotReducedDim with force = 0

### ISSUE THREAD

**Issue by ycl6** [alanocallaghan/scater#164]
Hi @Alanocallaghan 

I tried the latest version and unfortunately the _tweak_ mentioned in https://github.com/slowkow/ggrepel/issues/180 doesn't resolve the issue raised in #162 and https://github.com/Alanocallaghan/scater/issues/152#issuecomment-889993137. I also found related issues raised in `ggrepel`'s repo.

But, I am able to confirm `force = 0` will disable the repel functionality. I put together a quick function to test this by adapting the codes from `plotReducedDim`. By default, `force = 1`, with `force = 0` the labels will be positioned directly over the given coordinates.

> force - Force of repulsion between overlapping text labels. Defaults to 1.

```R
add_label <- function(object, dimred, text_by = "label", text_size = 5, text_colour = "black") {
    text_out <- retrieveCellInfo(object, text_by, search = "colData")
    text_out$val <- as.factor(text_out$val)
    red_dim <- as.matrix(reducedDim(object, dimred))
    df_to_plot <- data.frame(red_dim[, seq_len(2), drop = FALSE])
    colnames(df_to_plot)[seq_len(2)] <- c("X", "Y")
    by_text_x <- vapply(split(df_to_plot$X, text_out$val), median, FUN.VALUE = 0)
    by_text_y <- vapply(split(df_to_plot$Y, text_out$val), median, FUN.VALUE = 0)

    ggrepel::geom_text_repel(data = data.frame(x = by_text_x, y = by_text_y, label = names(by_text_x)),
                             mapping = aes(x = x, y = y, label = label),
                             inherit.aes = FALSE, size = text_size, colour = text_colour, force = 0)
}

plotReducedDim(sce.paul, "TSNE", colour_by = "label") + add_label(sce.paul, "TSNE")
```

**Comment by alanocallaghan** [comment]
Interesting. When testing, I observed that the labels looked fine on the example plot you provided

**Comment by ycl6** [comment]
@Alanocallaghan 

Oh! That's interesting indeed.

Below is the code I use to plot. It produces the same plot as before with the text repelled away from centre. 
Looking at the suggestion in https://github.com/slowkow/ggrepel/issues/180#issuecomment-755411911, I also tried `point.size = NA` but that didn't work either.

```R
set.seed(0123210)
plotReducedDim(sce.paul, "TSNE", colour_by = "label", text_by = "label", text_size = 7, theme_size = 16)
```

```
scater_1.23.4
ggrepel_0.9.1
```

**Comment by alanocallaghan** [comment]
Okie doke. I'm going to transfer this text/code to that issue to avoid duplication
