### ISSUE TITLE
`plotDots` should document that `features=` can accept a factor to control the order

### ISSUE THREAD

**Issue by LTLA** [alanocallaghan/scater#166]
Or maybe we should just automatically convert it into an appropriately ordered factor. AFAICT we don't specify any ordering ourselves, so I guess **ggplot2** takes it upon itself to alphabetically order things. Maybe we should force it to respect the user's input order. (I suppose that whatever is decided here should also apply for `plotHeatmap()` if no clustering is requested.)

**Comment by ycl6** [comment]
Hi @LTLA 

That's really nice to know. I am adding `+ scale_y_discrete(limits = geneNames)` to force the resulting plot to show `geneNames` same as the input's order. Would be nice to see `plotDots` does this to a character vector for `features=`.

**Comment by alanocallaghan** [comment]
Good news: plotDots accepts an ordered factor

Bad news: this doesn't control the order, just the labels

``` r
library("scater")

counts <- matrix(rpois(100, 5), ncol = 10)
rownames(counts) <- paste("Feature", 1:10)
sce <- SingleCellExperiment(assays = list(counts = counts))
sce <- logNormCounts(sce)

plotDots(sce, features=factor(rownames(counts), levels = paste("Feature", 10:1)))
```

![](https://i.imgur.com/CuHtzxy.png)

``` r
plotDots(sce, features=factor(rownames(counts), levels = paste("Feature", 1:10)))
```

![](https://i.imgur.com/NAhS2gT.png)

Will fix shortly, probably means changing swap_rownames to actually swap out rownames rather than just doing a dodgy match

**Comment by LTLA** [comment]
I don't think `.swap_rownames` is the problem as it just no-ops here. Rather, it seems that `summarizeAssayAcrossGroups` respects the level ordering (i.e., returning Feature 10 as the first feature in your second call) but the construction of `evals_long` still uses the factor ordering (i.e., reporting Feature 1 as the first feature).

However, even the apparent correct behavior of `summarizeAssayAcrossGroups` cannot be relied on. This is because subsetting by factor behaves as if it were subsetting by the integer codes, and it is only coincidental that the first factor value (Feature 1) has the last factor level in your second call, and thus corresponds to the integer code 10.

I suppose this is why the use of factors was not documented as being something that a user could/should do. In fact, it is so incorrect that I wonder whether we should detect and coerce all factors into character vectors, just in case.

Anyway, the solution seems to be to do:

```r
    evals_long <- data.frame(
        Feature=rep(factor(features, unique(features)), ncol(num)),
        Group=rep(group.names, each=nrow(num)),
        NumDetected=as.numeric(num),
        Average=as.numeric(heatmap_scale$x)
    )
```

assuming that `features` is just a plain old character vector.

**Comment by alanocallaghan** [comment]
Yeah I gathered most of that, I rather meant for the ordering purpose. At the moment `features` is pretty flexible in that it'll take numeric/character/logical/factor and do... something with each. I like the flexibility of being able to use whatever type input, and it's not particularly trick to handle properly by just converting each to character/factor with some checks.

Ah, I didn't realise that `summarizeAssayAcrossGroups` was also just doing bare indexing (therefore catching the integer bug). Will work around that.

**Comment by alanocallaghan** [comment]
I want to try to add a proper test for the heatmap(s) before pushing to bioc but master should at least not scramble data any more.

**Comment by alanocallaghan** [comment]
`rownames([pheatmap_object]$gtable$grobs[[2]]$children[[1]]$gp$fill)` per f78c03e. Should be on bioc presently
