### ISSUE TITLE
Handling genes with zero expression when using `scale = TRUE` in `plotDots()`

### ISSUE THREAD

**Issue by ycl6** [alanocallaghan/scater#167]
When using `scale = TRUE` in `plotDots()`, including genes that are not expressed in any of the cells will cause an error in `.heatmap_scale()`. 

```
Error in seq.default(zlim[1], zlim[2], length.out = length(color) + 1L) : 
  'from' must be a finite number
```

Maybe adding additional checks in `plotDots()` to remove such genes if `scale = TRUE`?

**Comment by alanocallaghan** [comment]
I don't really want to automagically remove features so will probably just add an informative error message, something like this:

``` r
library("scater")

counts <- matrix(rpois(100, 5), ncol = 10)
counts[1:5, ] <- 0
sce <- SingleCellExperiment(assays = list(counts = counts))
sce <- logNormCounts(sce)

plotDots(sce, features=1:10, scale = TRUE)
#> Error in .heatmap_scale(ave, center = center, scale = scale, color = color, : Cannot include non-expressed genes when scale=TRUE.
```

**Comment by ycl6** [comment]
Hi @Alanocallaghan That's a good idea, users will know they have to make the necessary changes to their inputs.

**Comment by alanocallaghan** [comment]
I count this as fixed now, feel free to reopen if not though
