### ISSUE TITLE
plotGroupedHeatmap not colouring appropriately.

### ISSUE THREAD

**Issue by ellispatrick** [alanocallaghan/scater#176]
Hi,

I recently updated my packages for the new Bioconductor release. When I use plotGroupedHeatmap the colours are various shades of blue. As far as I can tell this is because the eventual call to pheatmap uses "colour" as opposed to "color".

Let me know if I need to shoot you through an example. Otherwise any help/feedback would be appreciated (I do dumb things).

Cheers,
Ellis

**Comment by alanocallaghan** [comment]
Yep exactly right, thanks for the detailed bug report. Fix is pushed to devel and release now
