### ISSUE TITLE
plotPCA not coloring points

### ISSUE THREAD

**Issue by lambdamoses** [alanocallaghan/scater#184]
Ever since your last push to address the deprecation of `aes_string()`, `plotPCA()` is no longer coloring the points and the `color` and `colour` arguments have no effect. When I used debug mode, I think this is the culprit: https://github.com/Alanocallaghan/scater/blob/02b84e812a28e790ce2d46083cb00c7d4279e116/R/plotReducedDim.R#L222

There's the `colour_by` column in `df_to_plot_big`, but that column is not used when building the plot.

**Comment by lambdamoses** [comment]
Also, I saw that you used `.data$..scaled..`. I got a warning that `..scaled..` is deprecated, use `after_stat()` instead.

**Comment by alanocallaghan** [comment]
Thanks, just forgot to change one of the uses of get_point_args
