### ISSUE TITLE
Adding alias to exprs_values argument

### ISSUE THREAD

**Issue by antagomir** [alanocallaghan/scater#186]
Some other packages use `assay_name` as the argument to choose the assay for plotting SE objects. 

The `assay_name` refers more explicitly to assays than `exprs_values`. I would therefore suggest to include an alias  `assay_name` as an alternative to `exprs_values`.

**Comment by antagomir** [comment]
We can prepare a PR if this suggestion is accepted.

**Comment by alanocallaghan** [comment]
I think `assay_name` is much clearer, I might even deprecate the `exprs_values` equivalents eventually

**Comment by antagomir** [comment]
PR created #187
