### ISSUE TITLE
Argument naming: "assay_name" (scater) vs. "assay.type" (scuttle)

### ISSUE THREAD

**Issue by antagomir** [alanocallaghan/scater#189]
We recently changed the argument name from `exprs_values` to `assay_name` in _scater_ in PR #187 . This is in sync with mia package family, which uses `assay_name` as well. 

The _scuttle_ package is also using `exprs_values`, and I proposed a similar change in [scuttle issue #21](https://github.com/LTLA/scuttle/issues/21#issuecomment-1416688770). The maintainer has decided to prefer dot arguments (`assay.type`) instead, and has aliases for past underscore arguments to keep the code functional.

That would be a bigger change as it would affect other arguments, too. I would be ready to consider that for mia/miaViz/miaTime/miaSim etc. packages in order to align the conventions. But that would seem to make sense only if both _scater_ and _scuttle_ would converge to the same. If these two packages will have different argument names, we will probably keep mia* as is, and consider additional aliases to support interoperability with both.

Just wanted to cross-check this before proceeding. Is moving to dot arguments something that the _scater_ package could consider?

**Comment by Alanocallaghan** [comment]
Sure, if you want to change from underscore to dot then try get it in before the next bioc release so I don't have to deprecate anything

**Comment by alanocallaghan** [comment]
Sure, if you want to change from underscore to dot then try get it in before the next bioc release so I don't have to deprecate anything

**Comment by alanocallaghan** [comment]
I think this is resolved now
