### ISSUE TITLE
Gene names in nmf basis

### ISSUE THREAD

**Issue by liron27** [alanocallaghan/scater#192]
Hello

I am trying to run runNMF from scater and would appreciate your help.

I have a seurat object that I converted to SingleCellExperiment using:

 object.sce<-as.SingleCellExperiment(object.seurat)

Then I run runNMF:

`res<- runNMF(object.sce,ncomponents= 10, ntop = 1000)`

I get the nmf.out via reducedDim

`nmf.out <- reducedDim(res,"NMF")`

 and to get the basis

`nmf.basis<-attr(nmf.out,"basis")`

The problem is:
 the nmf.basis rows correspond to the genes but they are not annotated
 (see picture attached). I don't know the order of the genes (it takes
 the top 1000 variable genes).

Any help?
Thanks,
Liron

**Comment by alanocallaghan** [comment]
Sorry just circling around to this now. Your picture seems to be missing

**Comment by alanocallaghan** [comment]
A fix is on the way to bioc devel
