### ISSUE TITLE
PlotGroupedHeatmap - column clustering

### ISSUE THREAD

**Issue by angkoomin** [alanocallaghan/scater#195]
Hi there,

I'm trying to turn off the column clustering. However, with the code below, I'm still getting the dendrogram and column clustering. Is there a way of me ordering it manually?

``
plotGroupedHeatmap(cdScFiltAnnot[,1:100], features = geneNames, group = "NewLabel", 
                         clustering_method = "ward.D2",
                         border_color = "black", color = c_heatmap_col, fontsize = 8, angle_col = 0,
                         center = TRUE, scale = TRUE, zlim = c(-2, 2), main = "Row-scaled", silent = T,
                         cluster_rows = FALSE, 
                         cluster_columns = FALSE
                         )
``

I also tried this:

``
plotGroupedHeatmap(cdScFiltAnnot[,1:100], features = geneNames, group = "NewLabel", 
                         clustering_method = "ward.D2",
                         border_color = "black", color = c_heatmap_col, fontsize = 8, angle_col = 0,
                         center = TRUE, scale = TRUE, zlim = c(-2, 2), main = "Row-scaled", silent = T,
                         cluster_rows = FALSE, 
                         column_order = order(as.numeric(cdScFiltAnnot$NewLabel))
                         )
``

It still does not work.

Thanks

**Comment by alanocallaghan** [comment]
Can you provide a reproducible example, please?

**Comment by alanocallaghan** [comment]
```r
example_sce <- mockSCE()
example_sce <- logNormCounts(example_sce)
example_sce$Group <- paste0(example_sce$Treatment, "+", example_sce$Mutation_Status)

plotGroupedHeatmap(example_sce, features=rownames(example_sce)[1:10],
         group="Group", cluster_cols=FALSE)
```
