### ISSUE TITLE
add a half violin function

### ISSUE THREAD

**Issue by shangguandong1996** [alanocallaghan/scater#198]
Dear Developer

I am wondering whether you can add a function which can support plot half vilion like Seurat. I believe it can be useful when you show some gene expression in same cluster in two condition.

![图片](https://github.com/alanocallaghan/scater/assets/22555126/0eca067d-f8b9-479a-a50c-e3bc225303d8)

Best wishes

Guandong Shang

**Comment by alanocallaghan** [comment]
I would favour this type of plot over half violins https://github.com/alanocallaghan/scater/issues/175

**Comment by shangguandong1996** [comment]
Thanks, this type is what I want :)

**Comment by shangguandong1996** [comment]
Hi, dear developer
It seems that the `fill_by` parametes is in the `plotColData`. I am wondering `plotExpression` whether have this parameter.
