### ISSUE TITLE
minor comment for the documentation of normalize()

### ISSUE THREAD

**Issue by davismcc** [alanocallaghan/scater#20]
_From @friedue on April 19, 2017 15:6_

The function normalize.SCESet() has the default parameter `recompute_cpm = TRUE` - the current help text does not mention that the additional prerequisites for this parameter are (i) the presence of actual values within `cpm(sceSet)` and (ii) `exprs_values` must be set to “counts”. 

Since the default of the function that creates an sceSet object is to store cpm values in the `exprs()` slot, I was puzzled why `normalize()` would not re-compute the cpm values because I wasn't aware that they needed to be actually stored in the dedicated cpm() slot.

_Copied from original issue: davismcc/archive-scater#107_

**Comment by LTLA** [comment]
The latest `normalize` method no longer has a `recompute_cpm` option. Users can explicitly calculate CPMs using `calculateCPM`, which will respect the size factors if directed to do so.
