### ISSUE TITLE
runPCA Target Rank Error or Additional Right Arguments Warning

### ISSUE THREAD

**Issue by DarioS** [alanocallaghan/scater#205]
I have recently started seeing warnings and errors from `runPCA`. Sometimes, just a warning and resulting matrix looks O.K.

```r
Warning message:
In value[[3L]](cond) :
  Error: Error in initializeCpp(x@seed, ...): expected no additional right arguments for 'DelayedNaryIsoOp', falling back
  to an unknown matrix
```

Also, can be an error that locks R terminal, 100% single CPU usage according to `top` and

```r
Error in rsvd.default(x, k = k, nu = nu, nv = nv, ...) : 
  Target rank is not valid!
In addition: Warning messages:
1: In check_numbers(x, k = k, nu = nu, nv = nv) :
  more singular values/vectors requested than available
2: In value[[3L]](cond) :
  Error: Error in initializeCpp(x@seed, ...): expected no additional right arguments for 'DelayedNaryIsoOp', falling back
  to an unknown matrix
```

I am running R version 4.3.1 with scater version 1.30.1. In case it matters, the error-generating command was:

```r
all <- runPCA(all[, all$cellType == "Fibroblasts"], ncomponents = 10, subset_row = fibroVar, assay.type = "merged",
              name = "mergedFibroPCA", BPPARAM = MulticoreParam(8, RNGseed = 4444))
```

**Comment by LTLA** [comment]
Post a minimum reproducible example; I'm curious as to what delayed operations triggers those warnings.

Can't comment on the session lock. You'll have to `debug()` to track down the specific line; especially if an error was raised out of RSVD, then control should have been returned to the user at that point. Suggest verifying that this occurs outside of Rstudio.

**Comment by DarioS** [comment]
Thanks. After about one hour, I regained control of R terminal and additionally saw:

```r
Error during wrapup: negative length vectors are not allowed
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

The reason was I subset cells and assigned to the same variable.

```r
allHuman <- runPCA(allHuman[, allHuman$cellType == "Tumor"], assay.type = "merged", name = "mergedCancerPCA")
allHuman <- runPCA(allHuman[, allHuman$cellType == "Fibroblasts"], assay.type = "merged", name = "mergedFibroPCA")
```

In the second invocation, none of the cells are fibroblasts because it was overwritten by the tumour subset in step 1. Can I do per cell type PCA and UMAP without duplicating the SingleCellExperiment object? In this data set, I have only two cell types (cell culture) and would like both to have independent two-dimensional coordinates for separate dimension reduction plots. Perhaps not because the number of cells in all matrices in a SingleCellExperiment needs to be the same.

Regardless, the first invocation gives a warning. It's because the input data is DelayedMatrix (i.e. output format of scMerge). I tried `mockSCE` with various sizes but couldn't get it to trigger the warning.

```r
> class(assay(allHumanCancerMini, "merged"))
[1] "DelayedMatrix"
attr(,"package")
[1] "DelayedArray"
> runPCA(allHumanCancerMini, ncomponents = 10, subset_row = varGenes, assay.type = "merged")
Warning message:
In value[[3L]](cond) :
  Error: Error in initializeCpp(x@seed, ...): expected no additional right arguments for 'DelayedNaryIsoOp'
> assay(allHumanCancerMini, "merged") <- as.matrix(assay(allHumanCancerMini, "merged")) # Ordinary matrix. No warning.
```

**Comment by LTLA** [comment]
I'm really going to need an MRE to fix this. See if you can call **scMerge** on a mocked-up matrix.

**Update:** At least I think I know why the warning happens; it's probably because someone did a subset assignment into a `DelayedArray`. I don't have a C++-side representation for this, hence the warning and the fallback.

**Comment by DarioS** [comment]
I can't trigger it on any data set apart from my real one. It doesn't seem to be due to subset-and-assign.

```r
library(DelayedArray)
m <- matrix(1:10000, ncol = 100)
m <- DelayedArray(m)
m <- m[, 1:50] # No error.
```

**Comment by alanocallaghan** [comment]
It reads like a request for more PCs than are mathematically possible, but hard to tell without an example

**Comment by DarioS** [comment]
O.K. mister, you have a deal. Let's just say that you're not looking at unpublished data, wink, wink.

```r
library(scater)
options(timeout = Inf) # Avoid timeout.
download.file("https://www.maths.usyd.edu.au/u/dario/test.RData", "/tmp/test.RData") # Assuming Linux file system.
load("/tmp/test.RData")
runPCA(allHumanFibro, subset_row = fibroVarGenes, assay.type = "merged", name = "mergedFibroPCA")
```
Best wishes for pinpointing this edge case. Let's hope that it is not server configuration dependent.

**Comment by LTLA** [comment]
Subset assignment, not subset and assignment. The following reproduces the warning, but not the error or the hang:

```r
library(DelayedArray)
y <- DelayedArray(matrix(runif(20000), ncol=50))
y[y > 0.5] <- 1

library(BiocSingular)
library(BiocParallel)
all <- runPCA(y, rank = 10, BPPARAM = MulticoreParam(8, RNGseed = 4444))
```

Just ignore the warning for now, I don't think it's relevant. 

Anyway, your dataset is too big (21 GB!), I don't have the bandwidth at home. Can you make it more minimal?

**Comment by DarioS** [comment]
Thanks for getting me started. I can trigger target rank not valid by making a subsetting mistake that removes all columns.
```r
library(DelayedArray)
library(SingleCellExperiment)
library(scater)
y <- DelayedArray(matrix(runif(20000), ncol=50))
sce <- mockSCE(50, 400, 0)
rownames(y) <- rownames(sce)
colnames(y) <- colnames(sce)
assay(sce, "merged") <- y
sce <- runPCA(sce[, rep(FALSE, ncol(sce))], ncomponents = 5, exprs_values = "merged")
```
It's a different message to when the input is a plain matrix rather than a delayed one.

**Comment by LTLA** [comment]
I improved the warning message so that it doesn't have the word "Error", and thus should be less alarming.

As for the actual error: I suspect that this is a consequence of the size of your dataset, R's parallelization mechanism, and recent changes to **DelayedArray**'s matrix multiplication algorithm. You may be able to reproduce your problem without any **BiocSingular** involvement at all. Something like:

```r
y <- x[fibroVar,]
y <- y - rowMeans(y)
y <- t(y)
setAutoBPPARAM(MulticoreParam(8, RNGseed = 4444))
out <- rsvd::rsvd(t(y, k = 10, nu = 10, nv = 10)
```

P.S. `scater::runPCA` uses `BiocSingular::FastAutoParam`, which dynamically switches between IRLBA and randomized SVD depending on the size and representation of the dataset, see `?FastAutoParam` for the dispatch details. This is why the error message is different depending on whether you supply a `DelayedArray` or not.

**Comment by alanocallaghan** [comment]
Closing as I don't think it's a scater problem, but I am open to being convinced otherwise
