### ISSUE TITLE
Box plot instead of violin plot

### ISSUE THREAD

**Issue by TuomasBorman** [alanocallaghan/scater#207]
Hello,

I am one of the developers of [mia* packages](https://bioconductor.org/packages/release/bioc/html/mia.html). scater package is important part of mia framework.

The plotExpression() and plot*Data() functions currently visualize the data using violin plots. We have received couple requests for similar functions that use a box plot layout instead. I think adding the functionality directly to these scater functions might be the best option. What do you think, would it be good idea?

BR,
Tuomas Borman

**Comment by alanocallaghan** [comment]
I'm fine with this in principle but can't guarantee I'll move on it quickly. Feel free to draft a PR and I'll have a look

**Comment by TuomasBorman** [comment]
Sure, I will be able to do that in couple of days

**Comment by alanocallaghan** [comment]
Resolve #208
