### ISSUE TITLE
Add function for feature annotation from `org.Xx.eg.db` objects

### ISSUE THREAD

**Issue by davismcc** [alanocallaghan/scater#22]
_From @davismcc on April 14, 2017 15:33_

Guards against future deprecation of Biomart and allows annotation without a network connection.

_Copied from original issue: davismcc/archive-scater#105_

**Comment by LTLA** [comment]
People can just do this themselves, it's a handful of lines:

```{r}
library(org.Mm.eg.db)
keys <- "ENSMUSG00000029322"
anno <- mapIds(org.Mm.eg.db, keys=keys, keytype="ENSEMBL", column="SYMBOL")
```

... for gene symbols, and:

```{r}
library(TxDb.Mmusculus.UCSC.mm10.ensGene)
loc <- mapIds(TxDb.Mmusculus.UCSC.mm10.ensGene, keys=keys, 
    keytype="GENEID", column="CDSCHROM")
```

... for gene chromosomal locations.
