### ISSUE TITLE
tximport 1.3.5 can import .h5a kallisto abundance files

### ISSUE THREAD

**Issue by davismcc** [alanocallaghan/scater#23]
_From @mikelove on December 19, 2016 18:32_

see here:

https://github.com/Bioconductor-mirror/tximport/blob/master/R/tximport.R#L36

_Copied from original issue: davismcc/archive-scater#90_

**Comment by davismcc** [comment]
Very cool - thanks, Mike!

**Comment by LTLA** [comment]
@mikelove, is it fair to say that _scater_'s `readSalmonResults`, `readKallistoResults` and `readTxResults` can be discarded in favour of constructing a `SingleCellExperiment` directly from the output of _tximport_?

**Comment by mikelove** [comment]
Should be. The goal of `tximport` will be to support and unify the import of all information from transcript abundance quantifiers into R/Bioc.

Another note: `tximport` is lightweight and has no dependencies. We are building `tximeta` now, and it's submitted to Bioc, which will produce a *SummarizedExperiment* from Salmon quantifications with transcript/gene ranges and annotation metadata populated by examining the SHA-256 hash of the transcriptome and comparing to known transcriptomes. It's in beta, but I want to make this work for as many cases as possible. This has loads of dependencies, basically the entire Bioc annotation infrastructure. But the output is pretty cool:

https://github.com/mikelove/tximeta

**Comment by LTLA** [comment]
Okay. Does `tximport` already have a function to directly create an SE object from the pseudo-aligner output? I can see _DESeq2_ output, so it should be fairly trivial to have an SE creator as well (which may be even more generally useful). This would then allow a fairly standard `as` conversion to a SCE object.

**Comment by mikelove** [comment]
I'd be happy to add an argument to `tximport` that would wrap up the matrices into an SE, with rownames and colnames propagating. The `countsFromAbundance` element is important, as it changes whether or not the length matrix should be used as an offset or not. I could just add that to `metadata(se)$countsFromAbundance` I suppose.

**Comment by LTLA** [comment]
Hm. In the context of scRNA-seq exploratory analyses, most methods will be working off some transformed data. As a general rule, they're not model-based so they're not capable of considering offsets. What would be the most appropriate count matrix to return in such cases?

**Comment by mikelove** [comment]
If the counts are proportional to gene length, then I prefer `countsFromAbundance="lengthScaledTPM"`. The way to think of this is, it's very close to the original counts but with gene length variation regressed out. Gene length can change across samples due to bias or due to isoform switching, and this accounts for both.

If the counts are not proportional to gene length (3' tagged perhaps), then you should just use the original counts `countsFromAbundance="no"`.

**Comment by LTLA** [comment]
Okay, that's helpful. I think I will purge the obsolete functions from _scater_, and then add a recommendation of how to use _tximport_ in the vignette based on this discussion. To this end, if _tximport_ could also have an SE output function, that would make the coercion to SCE a lot easier.

@davismcc Any thoughts before I swing the axe? Also, on a related note: is `runKallisto` and `runSalmon` actually useful to anyone? I'd imagine that people are running these pseudo-aligners on clusters via SLURM or LSF job submissions, especially if speed was an issue in the first place...

**Comment by LTLA** [comment]
See 94afa2e2af879621f4f889df48fb6bad5713dde3. All functions related to transcript abundance input now refer to `readTxResults` (which is a simple wrapper around _tximport_), with an additional `full_length` argument based on the discussion above. I don't know whether the storing of bootstrap replicates is important, but if this is necessary, it seems like something that should be added in the _tximport_ side for broadest applicability.

**Comment by mikelove** [comment]
We already import inferential replicates (bootstraps or Gibbs sampling) if they are there and those go into a list of matrices called infReps. I’ll be providing more features for this soon, like infReps summarized to gene level, in this devel cycle. You can see how it works by looking at the tximport vignette where we import the Gibbs or bootstrap data.

**Comment by LTLA** [comment]
Yes, I saw that in `?tximport`; good to know that they're the same thing. Hm. I guess I should add an option to put these in the SCE object, though it's kind of hard to figure out how they fit... guess I could throw them in as separate assays.

**Comment by mikelove** [comment]
Looping back to _"Does tximport already have a function to directly create an SE object"?_

On second thought, I think I should leave this out of `tximport`, as it is kind of desirable that `tximport` has no imports/depends. 

My plan will be to build out `tximeta` so that it can take any quantifier as input and will output an SE. It's going to be in flux for a few more months, so you may just want to wrap up `tximport` output as an SE on your end for now.

I do think you'll see an advantage later on using `tximeta` as you'll get ranges for free (and worst case the output will be un-ranged SE).

**Comment by LTLA** [comment]
Okay. If using `tximeta` is as easy as you say, then I can get rid of `scater::readTxResults` entirely.

**Comment by mikelove** [comment]
I just pushed v0.99.8 of `tximeta` which should return SE for anything that `tximport` supports.

It's only on GitHub now but should be in devel before October (I hope!)

**Comment by mikelove** [comment]
tximeta is now part of Bioconductor and I’m nearly finished such that it will bring inferential replicates optionally summarized to gene level and optionally reduced to the sample variance.

**Comment by LTLA** [comment]
Okay, `readTxResults` is now deprecated and re-directs users to `tximeta::tximeta`.

I'm surprised that `tximeta` can't just accept a vector of file paths in `files` and auto-generate unique `names`. It would make it slightly more convenient if all we have are the files.

**Comment by mikelove** [comment]
Sure I can have a switch such that if coldata is a vector I just assume it is file paths and make unique names.

**Comment by mikelove** [comment]
I just added this (coldata can just be vector of file paths) in version 0.99.15, and pushed to Bioc and github
