### ISSUE TITLE
merge multiple sce

### ISSUE THREAD

**Issue by LuyiTian** [alanocallaghan/scater#25]
I saw a `mergeSingleCellExperiment` function but it has been commented out. Do you have future plans to add this functions? the `SingleCellExperiment` has rbind and cbind but it doesnot seems sufficient.

**Comment by LTLA** [comment]
What is insufficient about `cbind`? I never liked `mergeSCESet`, it was not entirely clear what was going on with respect to genes or metadata that were missing in some of the data sets. I've always felt that if you're combining very different data sets in your analysis, it is safer to be explicit about how conflicting names are handled. Obviously, if they are similar, then `cbind` will do the job.

**Comment by davismcc** [comment]
Hi Luyi,

That `mergeSingleCellExperiment` is just waiting for me to delete it when I clean up the package some more before the next Bioc release. We won't be developing that further or releasing it.

Now that `scater`'s using `SingleCellExperiment`, such a function is beyond the scope of `scater`. If you're not satisfied with the `cbind` capabilities for `SingleCellExperiment` objects, then that's something to take up with the `SingleCellExperiment` developers.

Best,
Davis

**Comment by LuyiTian** [comment]
@LTLA in the case when you want to merge two sce with different gene number but want to keep all the genes, I don't think this is covered by cbind. And in most cases the missing genes in one dataset are just filled with zero.

**Comment by LTLA** [comment]
Filling all the missing genes with zero counts sounds like a disaster. If they are missing, they should have `NA` values. Putting in zeroes gives the misleading impression that they are not expressed in one data set, whereas the truth is that those genes were not measured in the first place.

Of course, while you could put in `NA`s, you wouldn't be able to do much with the resulting matrix, as most downstream methods are not compatible with missing values. To me, the only sensible solution is to combine matrices for the common subset of genes, and this can be done using `cbind`.

I feel that a merging procedure (where the expression values for missing genes are filled in) is sufficiently unusual that it should be done explicitly in your analysis code, assuming it makes sense at all.
