### ISSUE TITLE
Make density ticks in PCA and tSNE plots optional?

### ISSUE THREAD

**Issue by chuanku** [alanocallaghan/scater#29]
Hi there,

I asked Aaron at a conference: Is it possible to to make the "density ticks" (ticks at x- and y-axis that show the positions of data points in a PCA or tSNE plot) optional? I think it would be nice to have this option.

Thank you for the great package!
Chuan

**Comment by LTLA** [comment]
Addressed in #39 at 1aa7a3e110d4602b41b6cc9ef9e2a1b19eeac45a.
