### ISSUE TITLE
Error when plotting more than 2 components with PlotPCA

### ISSUE THREAD

**Issue by campsj** [alanocallaghan/scater#31]
I recently started using SingleCellExperiment and the newest version of scater but I can't plot a PCA with more than two components anymore now. I get this error message:

> Error in plotReducedDim(object, ncomponents = ncomponents, use_dimred = "PCA", : ncomponents to plot is larger than number of columns of reducedDimension(object)

**Comment by LTLA** [comment]
This should be fixed in 40e4286a5147de9f41af562df0870bb5363fe70a, waiting for the PR merge.

**Comment by campsj** [comment]
Thanks for the fast response
