### ISSUE TITLE
Add Rtsne to imports or dependencies?

### ISSUE THREAD

**Issue by Shians** [alanocallaghan/scater#33]
The plotTSNE function does not work without Rtsne, but Rtsne is only in suggests and not depends or imports.

**Comment by LTLA** [comment]
This is probably a deliberate decision, to avoid loading in more packages than required for analyses that don't need plotting. _scater_ already loads in an annoyingly large number of packages, and people might have no intention of ever making a _t_-SNE plot for a particular analysis.
