### ISSUE TITLE
plotHighestExpr with feature_names_to_plot argument incorrectly sorts

### ISSUE THREAD

**Issue by Shians** [alanocallaghan/scater#37]
If feature_names_to_plot is set then the order will no longer be set according to average expression value. This is most likely due to ggplot's underlying handling of factor `aes`, which sorts alphabetically. You'll need to set the factor levels manually int he correct order (or using reorder) before passing it into ggplot to get the correct ordering.

**Comment by LTLA** [comment]
A reproducible example:

```{r}
library(scater)
counts <- matrix(rpois(10000, 1), ncol=10)
sce <- SingleCellExperiment(list(counts=counts))
rowData(sce)$blah <- paste0("Gene", seq_len(nrow(counts)))
plotHighestExprs(sce, feature_names_to_plot = "blah")
```

The factor levels are already appropriately ordered; the problem is actually due to the lack of consistency between `feature_names_to_plot` compared to `rownames(...)`. Fixed in #39.
