### ISSUE TITLE
plotScater too slow on large datasets

### ISSUE THREAD

**Issue by danfulop** [alanocallaghan/scater#40]
I tried running `plotScater()` blocked by dataset on a 4 dataset object. The function ran for ~20-30 mins without generating any output, at which point I stopped it.  The total object `dim` is 24439 by 27965 (that's after removing genes with no expression).  The 4 datasets comprise 10X data from 4 experimental conditions from one experiment.

**Comment by LTLA** [comment]
Could you set `debug(plotScater)` and check that the long-running step is:

```r
    seq_real_estate <- t(plyr::aaply(exprs_mat, 2, .fun = function(x) {
        cumsum(sort(x, decreasing = TRUE))
    }))
```

If this is the one taking all the time, then the fix is relatively easy. Otherwise it's all `reshape`ing and plotting functions afterwards, and there's nothing I can do for that.

**Comment by LTLA** [comment]
You can test the modifications in #42 and see if it's any faster.

**Comment by danfulop** [comment]
Thanks @LTLA!  I'll try to circle back to checking this.

**Comment by LTLA** [comment]
Closing, presuming there are no further issues.
