### ISSUE TITLE
Add option  to use irlba in the runPCA() for speeding up PC calculation 

### ISSUE THREAD

**Issue by ahy1221** [alanocallaghan/scater#48]
As the scRNA dataset size keep increasing day by day , I would suggest to add option to use irlba for PC calculation. Just as what scran did.

**Comment by LTLA** [comment]
This is something I have definitely thought about. But it will have to wait for the refactoring to finish.

**Comment by LTLA** [comment]
As it happens, I had some spare time so I just did it, see 475fa5bce1bcea4eb661de73b01d697009e1c788.
