### ISSUE TITLE
exprs() returning NULL

### ISSUE THREAD

**Issue by bruvellu** [alanocallaghan/scater#52]
Hi! After updating from 1.4.0 to 1.6.3 I noticed that `exprs(sce)` is returning `NULL`.

I create my SingleCellExperiment using `readKallistoResults`:

```R
> sce <- readKallistoResults(samples = kallisto_samples, directories = kallisto_dirs)
Kallisto log not provided - assuming all runs successful
Reading results for 91 samples:
................................................................................
...........
Using log2(TPM + 1) as 'exprs' values in output.
> exprs(sce)
NULL
```
I can workaround the issue using `assays(sce)$exprs` which returns the expression values.
```R
> assays(sce)
List of length 4
names(4): exprs counts tpm feature_effective_length
> assays(sce)$exprs
              L20105_Track-48323_R1 L20106_Track-48324_R1 L20107_Track-48325_R1 L20108_Track-48326_R1 L20109_Track-48327_R1
contig_1               0.000000e+00          0.000000e+00          0.000000e+00          0.000000e+00          0.000000e+00
contig_2               0.000000e+00          0.000000e+00          0.000000e+00          1.120067e+00          9.317398e-01
contig_3               0.000000e+00          0.000000e+00          0.000000e+00          2.480053e-01          4.600715e-01
...
```
I had a look at the `kallisto-wrapper.R` but didn't find anything unusual. Is `exprs` deprecated?

Let me know if you need further info to debug.

Cheers!

**Comment by LTLA** [comment]
`exprs()` itself is not deprecated, but now points to the `"logcounts"` assay, as this was the typical use.

In this specific case, we still store the log-transformed `"exprs"` in the output, but `exprs()` doesn't point there anymore. To get at it, you'll need to do `assay(sce, "exprs")` or the equivalent.

Admittedly, this is all a bit confusing, so in the next release, I will remove the `"exprs"` output completely from `readKallistoResults`, i.e., only counts and TPMs are reported. If users want log-transformed TPMs, they can do it themselves and store the results in a `"log_tpm"` assay or something.

Personally, I don't think it makes much sense to add an offset of 1 when log-transforming CPM, TPM or FPKM values, see my rant here: https://support.bioconductor.org/p/104943/#104963

**Comment by bruvellu** [comment]
Ah, I see now. Thanks for the detailed explanations!
