### ISSUE TITLE
No fData slot

### ISSUE THREAD

**Issue by ghoshal** [alanocallaghan/scater#53]
Hi,

I am using scater 1.6.3 for scRNAseq data normalization. After I run calcluateQCMetrics, no fData slot is getting generated. Please see the following code and error.

sce <- SingleCellExperiment(assays = list(counts = as(C04@raw.data, "dgCMatrix")))
exprs(sce) <- log2(calculateCPM(sce, use.size.factors = FALSE) + 1)
keep_feature <- Matrix::rowSums(exprs(sce) > 0) > 10
sce <- sce[keep_feature,]
is.mito <- grepl("^mt-", rownames(sce))
sce <- calculateQCMetrics(sce, feature_controls=list(Mt=is.mito))
fData(sce)

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘fData’ for signature ‘"SingleCellExperiment"’

Really appreciate any help available.

Thanks,

Bibaswan

**Comment by LTLA** [comment]
The feature-level metadata is stored as `rowData` in a _SummarizedExperiment_. `fData` is the corresponding function for the old _SCESet_ class (based on _ExpressionSet_).
