### ISSUE TITLE
Error when trying to read 10x results

### ISSUE THREAD

**Issue by TChan92** [alanocallaghan/scater#54]
Hi, I have a few directories with 10x data in them. They each have barcodes.tsv, genes.tsv and matrix.mtx.
 When I run read10xResults(data_dirs,min_mean_gene_counts = 1, min_total_cell_counts = 1), I get: 
`Error in .colSums(data_mat): argument "m" is missing, with no default`

My R environment looks like 
![screen shot 2018-04-17 at 10 52 52 am](https://user-images.githubusercontent.com/11138329/38887388-8d1a1cba-422d-11e8-92d8-3fd4e0955f18.png)

The data I'm using is from https://support.10xgenomics.com/single-cell-gene-expression/datasets

**Comment by LTLA** [comment]
Yes, this is a bug when `min_total_cell_counts` is set. I suggest keeping it `NULL` and doing your filtering on the returned object, it doesn't make much difference to efficiency anyway. 

We're very close to the next release date, so I won't bother to fix this in the current release. The next release has changed the underlying code completely and this is no longer an issue.
