### ISSUE TITLE
Change color - plotTSNE

### ISSUE THREAD

**Issue by ltosti** [alanocallaghan/scater#56]
Hi there,

I know plotTSNE returns a ggplot object so I tried to change the color of the plot by adding: 

`plotTSNE(sce, colour_by="ACTB") + scale_fill_gradient2(low='red', mid ='white', high ='blue')`

But I get this error:

`Scale for 'fill' is already present. Adding another scale for 'fill', which will replace the
existing scale.`

Any idea about how to solve this?

Thanks!

**Comment by LTLA** [comment]
Is than an error or a warning? It sounds like a warning to me, tell you that the existing scale is being overwritten. If it's an error, please provide a reproducible example, e.g., using the _scRNAseq_ package.

**Comment by ltosti** [comment]
Hi @LTLA ,

Thanks for the very quick reply. Yes, it is a warning, my mistake. 
I realised I was not using `scale_fill_gradient2` properly and instead of having 3 colours I was getting some shades of blue. Everything was fixed after specifying the midpoint. Sorry about that!
