### ISSUE TITLE
CalculateTPM for UMI counts

### ISSUE THREAD

**Issue by kawairine** [alanocallaghan/scater#58]
Hi,

 In the manual it has mentioned that I have UMI counts I shall leave effective_length=NULL, yet when I ran the function, it gave me error saying: "effective_length argument is required if computing TPM from counts". Hence, I am not sure if I should still calculate effective length.

Thank you!

**Comment by LTLA** [comment]
Are you using the latest version? That is, the one on the Github repository?

**Comment by LTLA** [comment]
I'm going to close this, as the problem should not exist with the latest version of _scater_.
