### ISSUE TITLE
plotPlatePosition inverts rows

### ISSUE THREAD

**Issue by ethering** [alanocallaghan/scater#59]
Hi,
I've either misinterpreted the parameters for plotPlatePosition, or there's a bug which gives plot_position a reversed 'columns' factor.
Here's my code, using the Tung test data ([https://github.com/hemberg-lab/scRNA.seq.course/tree/master/tung](url)) that replicates it.

```
source("https://bioconductor.org/biocLite.R")
biocLite("SingleCellExperiment")
biocLite("scater")
library(scater)
setwd("~/single_cell/training")

reads <- read.table("tung/reads.txt", sep = "\t")
anno <- read.table("tung/annotation.txt", sep = "\t", header = TRUE)
reads <- SingleCellExperiment(
  assays = list(counts = as.matrix(reads)), 
  colData = anno
)

reads <- calculateQCMetrics(reads)
plotPlatePosition(reads, plate_position = reads$well, colour_by = "well")
```
As you can see, the rows are in the reverse order (wells from row 'A', plotted in row 'H', wells from row 'B' plotted in row 'G', etc.
Is this a bug, or am I doing something wrong here?

![plotplateposition](https://user-images.githubusercontent.com/325426/43010254-d9693a52-8c37-11e8-9563-6e7aa891b16e.jpeg)

**Comment by LTLA** [comment]
Well spotted. This should be fixed in 696bb22e3f7d8422781dd3d570e2a1641cd83664.
