### ISSUE TITLE
Error in checkSlotAssignment(object, name, value) : assignment of an object of class “CompressedGRangesList” is not valid for slot ‘rowRanges’ 

### ISSUE THREAD

**Issue by DrLucyMac** [alanocallaghan/scater#62]
Hi there,

I am trying to run tSNE+kmeans clustering on a SCE object but Im getting the following error. 

`#Perform dimensional reduction
macro <- runTSNE(macro, rand_seed = 1, return_SCE = TRUE)`

`Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “CompressedGRangesList” is not valid for slot ‘rowRanges’ in an object of class “RangedSummarizedExperiment”; is(value, "GenomicRanges_OR_GRangesList") is not TRUE`

Is there any way to fix this? I get this error whether i use runTSNE or plotTSNE. 

Cheers,
Lucy

**Comment by LTLA** [comment]
See the advice here:

https://support.bioconductor.org/p/101813/

**Comment by LTLA** [comment]
I'm assuming that this was resolved, so I'm closing this issue.
