### ISSUE TITLE
Inconsistency in function "normalise"

### ISSUE THREAD

**Issue by chelseaju** [alanocallaghan/scater#64]
Hi, Thank you for developing this package for processing the single-cell data. I have found many functions extremely useful. I noticed some inconsistency while trying out the "normalise" function.

My goal is to compare different dropout recovery methods, so I create a SingleCellExperiment object with different count matrices. I have the following code:

```
data("sc_example_counts")
data("sc_example_cell_info")
recovery_matrix <- matrix(rnorm(800000, mean = 5), nrow=2000, ncol = 40)

example_sce <- SingleCellExperiment(
	assays = list(counts = sc_example_counts), 
	colData = sc_example_cell_info)

example_sce_recovery1<- SingleCellExperiment(
	assays = list(counts = sc_example_counts,
				  recovery = recovery_matrix), 
	colData = sc_example_cell_info)

example_sce<- normalise(example_sce)
example_sce_recovery1 <- normalise(example_sce_recovery1)

assays(example_sce)$logcounts[1:5,1:5] == assays(example_sce_recovery1)$logcounts[1:5,1:5]

```
As expected, the normalized values from example_sce is exactly the same as those from example_sce_recovery1. However, when I swap the assay name, the results look different.

```
example_sce_recovery2<- SingleCellExperiment(
	assays = list(recovery = sc_example_counts,
			counts= recovery_matrix), 
	colData = sc_example_cell_info)

example_sce_recovery2 <- normalise(example_sce_recovery2,  exprs_values = "recovery")

assays(example_sce)$logcounts[1:5,1:5] == assays(example_sce_recovery2)$logcounts[1:5,1:5]

```

```
          Cell_001 Cell_002 Cell_003 Cell_004 Cell_005
Gene_0001     TRUE    FALSE    FALSE     TRUE     TRUE
Gene_0002    FALSE    FALSE    FALSE    FALSE    FALSE
Gene_0003     TRUE     TRUE     TRUE     TRUE    FALSE
Gene_0004     TRUE    FALSE     TRUE     TRUE     TRUE
Gene_0005     TRUE     TRUE    FALSE     TRUE     TRUE
```

Specifying the assay name in normalise function does not seem to work. I am wondering if you can help me resolve this issue. 

Thanks,
Chelsea

**Comment by LTLA** [comment]
Are you using the latest version?

**Comment by chelseaju** [comment]
Thanks for the quick reply. I am using R version 3.5.0, with scater_1.8.3.

**Comment by LTLA** [comment]
It's because you don't have size factors in `sce` - you should have seen a warning from the function. This means that the function needs to compute size factors using `librarySizeFactors`, which (in the release version) does not respond correctly to `exprs_values=`. This has been fixed in the devel version, but in the meantime, you can make it behave correctly by setting the size factors before calling `normalize`.

**Comment by chelseaju** [comment]
Thank you. It makes sense now.
