### ISSUE TITLE
readSparseCounts not exported in mac version

### ISSUE THREAD

**Issue by tohein** [alanocallaghan/scater#65]
Hi, 
it seems that readSparseCounts is not exported properly in the mac version

https://www.bioconductor.org/packages/release/bioc/bin/macosx/el-capitan/contrib/3.5/scater_1.8.3.tgz

Best regards,
Tobi

**Comment by LTLA** [comment]
It should not be exported at all in release 3.7. I only added it in 3.8 (i.e., _scater_ 1.9.*).
