### ISSUE TITLE
no readSparseCounts function

### ISSUE THREAD

**Issue by Ruismart** [alanocallaghan/scater#67]
I use biocLite("scater")  to install this package, but no readSparseCounts function found.
I try to use install_github("davismcc/scater") , but get error like this : 
![qq 20180928203840](https://user-images.githubusercontent.com/35186716/46208852-a6f1b280-c35e-11e8-8caf-29ccf34bf43e.png)

**Comment by LTLA** [comment]
Follow the instructions at https://bioconductor.org/packages/devel/bioc/html/scater.html.

**Comment by Ruismart** [comment]
Much appreciated！It works well with devel version.
