### ISSUE TITLE
invalid rownames length error when using SingleCellExperiment

### ISSUE THREAD

**Issue by gangcai** [alanocallaghan/scater#70]
```r
data("sc_example_counts")
data("sc_example_cell_info")
example_sce <- SingleCellExperiment(
    assays = list(counts = sc_example_counts), 
    colData = sc_example_cell_info
)
```

Error in `rownames<-`(`*tmp*`, value = c("Gene_0001", "Gene_0002", "Gene_0003",  : 
  invalid rownames length

**Comment by LTLA** [comment]
The same command works fine for me. Make sure you're using the current version of all Bioconductor packages (run `BiocManager::valid()` and fix any issues). If this doesn't help, follow the advice [here](https://support.bioconductor.org/p/101813/#102033).

**Comment by gangcai** [comment]
Thanks for the reply. I checked the version of Bioconductor, it's the developmental version Bioconductor 3.8. This might be the reason.

**Comment by LTLA** [comment]
3.8 is the correct version, so I assume that your existing installed packages are broken. Re-install all relevant packages, as per the advice in the link, and try creating an SCE in a fresh R session.

**Comment by gangcai** [comment]
Thanks, I updated the outdated packages, and now it works.
