### ISSUE TITLE
newSCESet fails to assign counts(scetset)

### ISSUE THREAD

**Issue by jeskowagner** [alanocallaghan/scater#72]
Hello,

First a disclaimer: I am working to reproduce data from a publication and am therefore using the obsolete function newSCESet from release 3.4 (version 1.2.0). More specifically, I would like to use calculateQCMetrics on the SCESet later on.
In this process, I am encountering an issue when using countData as input.
I am using the call 

> sce = newSCESet(countData = count.mat, phenoData = pdata, featureData = fdata)

My input (before conversion to AnnotatedDataFrame for readability): 

```
head(fdata)
               ens_id              chr strand  start      end
0610005C13Rik ENSMUSG00000109644   7     -1 45567794 45575327
0610006L08Rik ENSMUSG00000108652   7     -1 74818818 74853813
0610007P14Rik ENSMUSG00000021252  12     -1 85815448 85824550
0610009B22Rik ENSMUSG00000007777  11     -1 51685386 51688874
0610009E02Rik ENSMUSG00000086714   2      1 26445696 26459390

```

```
head(pdata)
     culture method
A02   Serum    NMT  
A03   Serum    NMT  
A04   Serum    NMT    
A05   Serum    NMT 
A06   Serum    NMT
```

```
count.mat[1:5,1:5]
              A02 A03 A04 A05 A06
0610005C13Rik   0   0   0   0   0
0610006L08Rik   0   0   0   0   0
0610007P14Rik  88  33  58  37  19
0610009B22Rik   0 145  73 111  32
0610009E02Rik   0   0   0   0   0
```

After conversion of fdata and pdata:
```
fdata
An object of class 'AnnotatedDataFrame'
  rowNames: 0610005C13Rik ... Zzz3 (48188 total)
  varLabels: ens_id chr ... end (5 total)
  varMetadata: labelDescription
```

```
pdata
An object of class 'AnnotatedDataFrame'
  rowNames: A02 A03 ... H09 (73 total)
  varLabels: culture method
  varMetadata: labelDescription
```

With this input, newSCESet crashes at line 199 ([of release 3.4](https://github.com/davismcc/scater/blob/RELEASE_3_4/R/SCESet-methods.R)) with the error:
> Error in .Primitive("[")(c(0L, 0L, 0L, 88L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,  : subscript out of bounds

Some further info:

```
nrow(count.mat)
[1] 48188

ncol(count.mat)
[1] 73
```

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux release 6.10 (Carbon)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] scran_1.2.2         BiocParallel_1.8.2  scater_1.2.0       
[4] ggplot2_2.2.1       Biobase_2.34.0      BiocGenerics_0.20.0
[7] purrr_0.2.5         data.table_1.11.8
```

Please excuse the long post. I would appreciate any hints on how best to approach this problem. If you suggest getting rid of newSCESet altogether, it would be very helpful if you could let me know whether the data will then still be comparable to the published processed data.

Thanks in advance!

**Comment by LTLA** [comment]
Your `newSCESet` call looks fine, so this is probably a bug inside the function. I daresay it's not the only bug, either... there's a reason why that class is obsolete, and we're using the `SingleCellExperiment` instead.

I only support bugfixes in the latest versions of the package; all older `RELEASE` versions are effectively frozen. Thus, the best option is to simply update your analysis scripts to use `SingleCellExperiment` objects. Most functions will return the same results; others will be different due to bug fixes or performance improvements (and possibly regressions, but I'm confident that these are few and far between).

Hopefully, you will get similar results to the published results using the latest version of the packages. In general, I wouldn't worry about exact reproducibility, bugfixes and tweaks will always change the results slightly. If the conclusions are qualitatively different, though, that is some cause for concern.

**Comment by jeskowagner** [comment]
Thanks @LTLA for the swift reply! I expected there there to be no more support for this function but figured it was worth trying. I will update the script accordingly then and hope for comparable results.
Thanks for your help.

**Comment by jeskowagner** [comment]
If anyone has the same problem in the future:
After further attempts to circumvent having to use `SingleCellExperiment` I noticed that I was ordering my count table different than in the original publication. Changing the order of the count table resolved the problem, although I do not know why.
