### ISSUE TITLE
masking functions from dplyr package

### ISSUE THREAD

**Issue by ddiez** [alanocallaghan/scater#74]
_scater_'s `filter`, `mutate`, `rename` and `arrange` are defined in a way similar to the same functions in _dplyr_ package. Unfortunately when loading _scater_ they mask each other. This seem to be due to these functions generics being defined using `standardGeneric()`. Since someone interested in using `scater::filter()` might also want to use `dplyr::filter()` this is a bit inconvenient. Would it be possible to just use e.g. `setGeneric("filter")`? (this would require adopting `dplyr::filter()` default arguments. Something like this seems to work:

```
setGeneric("filter")
setMethod("filter", "SingleCellExperiment", function(.data, ...) {
  head(.data) // dummy code
})
```

**Comment by LTLA** [comment]
Having to coordinate _dplyr_'s S3 and Bioconductor's _S4_ methods and generics would be a pain. Not impossible, but outside the realm of what I want to do (or find useful, for that matter).

Indeed, I have wanted to purge these functions from _scater_ for a very long time. This issue finally gives me some motivation to do so, provided I can find a suitable home in another package.

**Comment by ddiez** [comment]
I wasn't actually using them right now so will not complain if they go away. Would it make sense for them to have a dedicated package for dplyr-like manipulation of SE (and maybe others) objects?

**Comment by LTLA** [comment]
Yes.

**Comment by lazappi** [comment]
You might want to talk to @sa-lee about this. He made plyranges which does this for `GRanges` objects (https://github.com/sa-lee/plyranges) and I think there was talk of doing something similar for `SummarizedExperiment`.

**Comment by LTLA** [comment]
Well, whoever gives me the green light for a PR first will get the PR.

**Comment by sa-lee** [comment]
@lawremi and I have been wanting to extend a tidy API for `SummarizedExperiment` (there's even an API spec on it in the plyranges wiki). I can open up a new repo if you want to put your stuff in there @LTLA (not sure how active biobroom is at the moment). This as good motivation as any to start working on it 😃 .

It might perhaps be worth placing the dplyr/tidyverse generics in their own Bioconductor package ala `BiocGenerics` called something like `TidyGenerics` so Bioconductor users can import directly from there (without necessarily having to depend on  dplyr/tidyverse). I guess @mtmorgan would have opinions on this.

**Comment by lawremi** [comment]
I think the API @sa-lee and I were proposing does not actually have any conflicting symbols with dplyr, since every name would be qualified by `_rows()` or `_cols()`.

**Comment by LTLA** [comment]
@sa-lee Yes, please open a repo. I'll chuck in everything tomorrow; what I have right now is probably akin to the `_cols()` functions. I'd like to move these functions out of _scater_ by the next release if possible.

**Comment by sa-lee** [comment]
Sounds good! I've just made a repo here: https://github.com/sa-lee/plyexperiment

**Comment by LTLA** [comment]
Great. I'm going to close this issue, noting that the masking will still persist into the next release until I finally remove the functions (following Bioconductor's usual deprecation procedures).

**Comment by alanocallaghan** [comment]
Since this is still somewhat inconvenient for the time being, an easy solution would be to provide a default method, eg:

```r
#' @export
setMethod("mutate", "ANY", function(object, ...) dplyr::mutate(object, ...))
```

Though this is obviously too late for the 3.9 release. It still seems like it would be more user-friendly for the deprecation period.

**Comment by LTLA** [comment]
I'll go one better and **remove them altogether**. From 3.10, at least; they're deprecated in 3.9.
