### ISSUE TITLE
make it known that scater can handle data generated by 10X Genomics

### ISSUE THREAD

**Issue by friedue** [alanocallaghan/scater#78]
Just saw that 10x Genomics has stopped supporting their own functions of reading their data into R; instead they're now promoting Seurat -- scater should probably be mentioned there, too. 

[https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/rkit](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/rkit)

**Comment by LTLA** [comment]
I and others have sent them emails about _DropletUtils_ in particular, to which they have not responded. You could try emailing them as well, but history suggests that they will not be receptive.

**Comment by friedue** [comment]
They have not responded at all? Strange, I've found their tech people to be highly responsive. I'll give it a shot!

**Comment by LTLA** [comment]
Well, best of luck. 

I'll just note that (i) _DropletUtils_ is the more relevant package for reading in 10X data (after which it can be analyzed by any package supporting `SingleCellExperiment` or even `SummarizedExperiment` inputs), and (ii) the devel version of _DropletUtils_ supports CellRanger version 3 output.

I'll close this for the time being, but if you get a response, feel free to update this thread.

**Comment by abcfrd** [comment]
Just for completeness sake: bioconductor is at least mentioned now! see [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/rkit)

I feel that the text I sent them was a little less terse, but seeing how long this took, this may be as good as it gets.

Again, just for reference, this is what I sent them:

Bioconductor offers a continuously growing number of packages to process and analyze data from single cell experiments including data generated on the 10X Genomics platform. An easy entry point to learning about the single-cell-capabilities of bioconductor is the simpleSingleCell package.
Instructions for installing the simpleSingleCell package can be found here: https://master.bioconductor.org/packages/release/workflows/html/simpleSingleCell.html
For a workflow to read in and process 10X Genomics Data using the PBMC data set, see the vignette here: https://master.bioconductor.org/packages/release/workflows/vignettes/simpleSingleCell/inst/doc/work-3-tenx.html
For an excellent tutorial on the different data visualization capabilities of the SingleCellExperiment-based packages, see, for example:  https://master.bioconductor.org/packages/release/bioc/vignettes/scater/inst/doc/vignette-dataviz.html 

Currently (Jan 2019), the development version of DropletUtils supports CellRanger version 3 output (https://master.bioconductor.org/packages/devel/bioc/html/DropletUtils.html).

**Comment by friedue** [comment]
no idea where that account (abcfrd) came from; it was, in fact, me posting this...
