### ISSUE TITLE
plotExpression change the order of plotting vars

### ISSUE THREAD

**Issue by macsalvin** [alanocallaghan/scater#80]
Hi,
there is a way to quickly change the order of my sample into the plotExpression graph?
I would like to switch them in order to have WT and then KO.

<img width="253" alt="img" src="https://user-images.githubusercontent.com/23176893/51277066-88163b00-19a4-11e9-91a6-3b63dbf0d197.png">

Thanks

**Comment by PeteHaitch** [comment]
```r
# Assuming the genotype is stored in a column of the colData called genotype
sce$genotype <- factor(sce$genotype, levels = c("WT", "KO"))
```
Then re-plotting should do it

**Comment by macsalvin** [comment]
This worked perfect, thanks a lot!
