### ISSUE TITLE
getting error by following tutorial of scater

### ISSUE THREAD

**Issue by deo999** [alanocallaghan/scater#81]
how to install scater  with bioconductor using  bioconda
hi  developer,

i want to use scater on  my machine with conda/bioconda  i am ale to install all packages except : 
conda install -c bioconda bioconductor-scater
conda install -c bioconda bioconductor-sc3  

 it giving following error:
PackagesNotFoundError: The following packages are not available from current channels:

  - bioconductor-scater

Current channels:

  - https://conda.anaconda.org/bioconda/label/gcc7/win-64
  - https://conda.anaconda.org/bioconda/label/gcc7/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to
 https://anaconda.org

and use the search bar at the top of the page.

please  help me so that i can use this tool.

Thanks

**Comment by LTLA** [comment]
You should take this up with the bioconda people, this does not seem to be a problem on our end.

**Comment by deo999** [comment]
ok i fix that now i am getting this error:
> exprs(sce.temp) <- assay(sce.temp, "exprs.magic") Error in (function (classes, fdef, mtable)  :    unable to find an inherited method for function ‘assay’ for signature ‘"SCESet", "character"’
--
 
  |

**Comment by LTLA** [comment]
It has been a long, long time since _scater_ used `SCESet` objects. If you are constructing `SCESet` objects, you are following out-of-date instructions with an out-of-date package installation.

The simplest solution is to install the latest version of R (3.5.2) and follow the instructions here:

https://bioconductor.org/packages/release/bioc/html/scater.html

If you must use bioconda, then I can only assume that they are supplying an ancient version of _scater_, in which case you should go complain about it to the bioconda folks. The current release version of _scater_ is 1.10.1; you can check what you have with `sessionInfo()`.

**Comment by deo999** [comment]
i m using current version and install with same link u provided, i just want to do following tutorial for data https://github.com/dpcook/scRNASeq-estrogen/blob/master/notebooks/05-clustering.md can you please guid how to do clustering with scater using latest version.

**Comment by LTLA** [comment]
Let's get the facts straight here.

- You are using R 3.5.2.
- You are using _scater_ 1.10.1.
- `BiocManager::valid()` reports no problems.

If these facts are all true, then your installation is fine. Our attention now turns to the linked tutorial. This line:

> ```sce <- readRDS("../output/sce.normalized.imputed.rds")```

... seems to load a `SCESet` object. As I intimated earlier, _scater_ (and indeed, many of the single-cell Bioconductor packages) has not used `SCESet` objects for a very long time. So your options are:

1. Get the maintainer of that tutorial to update it to use the `SingleCellExperiment` container.
2. If they do not, follow a different workflow that is up-to-date, e.g., [here](https://bioconductor.org/packages/simpleSingleCell).
