### ISSUE TITLE
Scater version 1.4.0

### ISSUE THREAD

**Issue by EDYAC** [alanocallaghan/scater#85]
Hello everyone,
How can I install the older version of Scater, version 1.4.0?
Thank you so much.

**Comment by LTLA** [comment]
Bioconductor packages are matched to specific versions of R, so you would need to get the corresponding version of R. _scater_ 1.4.0 was part of Bioconductor 3.5 (see versions [here](https://www.bioconductor.org/packages/3.5/bioc/html/scater.html)), so you would need R 3.4 (see [here](https://www.bioconductor.org/about/release-announcements/#release-versions)). Once you have this, you can follow the installation instructions [here](https://www.bioconductor.org/install/#Legacy).

Specific BioC/R versions can also be obtained as AMIs or Docker files [here](https://www.bioconductor.org/install/#preconfigured), if you can use these.
