### ISSUE TITLE
plotRLE() - all points at zero

### ISSUE THREAD

**Issue by lucygarner** [alanocallaghan/scater#87]
Hi,

When I run the following code, I get an RLE plot where the dots for each sample are at 0 and there are no coloured lines.  What could be the cause of this?

`qclust <- quickCluster(sceset.qc, min.size = 30)`
`sceset.qc <- computeSumFactors(sceset.qc, sizes = 15, clusters = qclust)`
`sceset.qc <- normalize(sceset.qc)`
`summary(sizeFactors(sceset.qc))`
`plotPCA(sceset.qc[endog_genes, ], colour_by = "plate", size_by = "total_features_by_counts", shape_by = "donor")`

`plotRLE(
    sceset.qc[endog_genes, ], 
    exprs_values = "logcounts_raw",
    colour_by = "plate"
)`

sceset.qc is my SingleCellExperiment object.

![image](https://user-images.githubusercontent.com/22564745/57981189-75804100-7a2c-11e9-9eb5-ed952ca1b6bd.png)

Best wishes,
Lucy

**Comment by LTLA** [comment]
Does `sceset.qc[endog_genes, ]` have any non-zero expression values?

**Comment by lucygarner** [comment]
Yes.  This is part of the "logcounts_raw" data frame.

![image](https://user-images.githubusercontent.com/22564745/58012335-24d01d00-7aec-11e9-8b5b-28f83aeb2a50.png)

**Comment by LTLA** [comment]
I would guess that, in your case, every cell has more than 75% zeroes, such that the first, second and third quartiles are all zero. This means that the IQR is zero, and all non-zero values are considered to be outliers (and subsequently not plotted when `style="minimal"`). If you want to see the outliers, set `style="full"`; but these plots won't be of much use when you have so many zeroes in the data. You should probably filter the SCE before plotting, i.e., subset by abundance in addition to using `endog_genes`.

**Comment by LTLA** [comment]
I'm going to assume that this was fixed.

**Comment by lucygarner** [comment]
Thanks for the advice - I just didn't use this plot in the end, as it wasn't sure if the high fraction of zeros indicated an issue with my data.
