### ISSUE TITLE
error in calculateQCMetrics

### ISSUE THREAD

**Issue by junha92** [alanocallaghan/scater#88]
I am running the following code, and there is a following error that I don't know the solution to

tmp <- SingleCellExperiment(list(counts = as.matrix(gliaAD)))
is.mito <- grepl("^mt-", rownames(tmp))
summary(is.mito)
is.spike <- grepl("^ERCC", rownames(tmp))
isSpike(tmp, "ERCC") <- is.spike
summary(is.spike)

tmp <- calculateQCMetrics(tmp, feature_controls=list(Spike=is.spike, Mt=is.mito))
Error in (function (exprs_mat, start, end, all_feature_sets, all_cell_sets,  :    unacceptable matrix type

 gliaAD is a standard singlecell UMI count data downloaded from GSE98969

**Comment by LTLA** [comment]
Have you checked if `as.matrix(gliaAD)` actually contains numeric values?

**Comment by junha92** [comment]
I performed 
m <- as.matrix(df)
class(m) <- "numeric"
but this matrix m has NA values..would that be the problem?

**Comment by junha92** [comment]
solved the problem! Thanks

**Comment by AlgabriY** [comment]
Hi junha92,
How did you solve it please?
