### ISSUE TITLE
change the order of genes in plotExpression

### ISSUE THREAD

**Issue by namhuynhnc** [alanocallaghan/scater#92]
I want to change the order of genes in plotExpression.
It always shows in ABC order but I want to show in my interest order.
How can I do it? Thank you

**Comment by LTLA** [comment]
This seems to be a ggplot2 thing, whereby it uses the panel ordering by factor levels. Kind of annoying but it should be easily fixable.

**Comment by namhuynhnc** [comment]
I found the way to fix it by modifying facet_wrap()
Thank you so much.
