### ISSUE TITLE
Pass colData to plotReducedDim output

### ISSUE THREAD

**Issue by robertamezquita** [alanocallaghan/scater#94]
Simple hack for enabling facetting downstream by user:

```
p <- plotUMAP(sce)
p$data <- as.data.frame(cbind(p$data, colData(sce)))

p +
    facet_grid(patient_id ~ time_id) +
    scale_fill_manual(values = cols)
```

Could be useful for enabling visualizing/faceting by other characteristics. Maybe this behaviour could be controlled by a "pass.colData = TRUE" arg in `plotReducedDim()`, where users who care about large ggplot2 instances can turn off the behavior.

**Comment by LTLA** [comment]
Pretty gross to muck around with _ggplot_'s internals. Fine for interactive hacks but I wouldn't put that in an analysis script. Better to add an option in all plotting functions to add arbitrary metadata fields into the underlying `data.frame`, anticipating that they will be used later by the user.

**Comment by LTLA** [comment]
`altexp` branch, 604f69a60d11aa746ea69a432b02d80cc72b9290

```r
library(scRNAseq)
sce <- ReprocessedAllenData()

library(scater)
sce <- normalize(sce, exprs_values="tophat_counts")
sce <- runPCA(sce)

gg <- plotReducedDim(sce, "PCA", colour_by="dissection_s",
    other_fields=c("driver_1_s", "Core.Type"))
gg + facet_grid(Core.Type ~ driver_1_s)
```

**Comment by robertamezquita** [comment]
👏👏👏
