### ISSUE TITLE
Vignette text outdated  and sc_example_counts is defunct.

### ISSUE THREAD

**Issue by amcdavid** [alanocallaghan/scater#95]
The `data(sc_example_counts)` appears to have been removed from devel, but the vignette still references it.

https://github.com/davismcc/scater/blob/8b68aed9921439dcf48fda8088bbae04f7daf1a4/vignettes/overview.Rmd#L39

FWIW, this also breaks one of my vignettes, and the `data` do seem like part of the public API for a package, so maybe should have gotten a Deprecation message for a version vs being removed without ceremony.

**Comment by LTLA** [comment]
Putting a deprecation message inside `data()` is a real pain, so I didn't do it. I wasn't expecting anyone else to depend on the data objects, but if they were, it's an easy swap out to `mockSCE()`.

**Comment by LTLA** [comment]
The data objects are back, after some disgusting hacks. But long-term use is with `mockSCE()`.

**Comment by amcdavid** [comment]
Thanks...the horrible hack is appreciated but probably all I really needed was an alias added to the documentation so that `?sc_example_counts` explains that it's defunct what to use instead.  Though I guess [Bioconductor guidelines](http://bioconductor.org/developers/how-to/deprecation/) say otherwise.

(And the horrible hack is actually pretty interesting to read!)
