### ISSUE TITLE
`use_size_factors` deprecation (`calculateCPM`)

### ISSUE THREAD

**Issue by jonathanronen** [alanocallaghan/scater#96]
Hi there
I was getting deprecation warnings like `Warning: ''use_size_factors='' is deprecated.`. The documentation told me to use `size_factors` instead (it says `use_size_factors	Deprecated, same as size_factors.`).

However, using `size_factors` instead of `use_size_factors` gave me errors like `length of 'size_fac' does not equal number of columns` elsewhere.

So, am I doing something wrong, or is this deprecation warning premature?

Thanks,
J.

**Comment by LTLA** [comment]
The message should have said `use_size_factors=TRUE` is deprecated (and actually, the same thing is true of `use_size_factors=FALSE`). This has been fixed and should continue to work **for now**.

In the future, you won't be able to give a logical scalar to `size_factors`. The main reason for this was it was difficult to code and difficult to explain to users - `use_size_factors` could be numeric or logical, and its effect changes depending on whether `x` is a matrix or a `SingleCellExperiment`.

The new status (with `size_factors`) is simpler. If you give us size factors, we'll use them. If you don't, we'll use size factors derived from the object. For a matrix input, these are based on the library sizes. For `SingleCellExperiment` instances, these are whatever are in the `sizeFactors()`.

**Comment by LTLA** [comment]
Closed by 28efd0443135f4a2309cc1e2b57c30560094ae9d.

**Comment by jonathanronen** [comment]
Thanks, @LTLA !
