### ISSUE TITLE
Reorder by descending `colour_by` values

### ISSUE THREAD

**Issue by robertamezquita** [alanocallaghan/scater#97]
Maybe add as an option or do as default - I find myself often doing the following pattern:

```
g <- plotReducedDim(sce, 'PCA', colour_by = 'CD3E')
g$data <- dplyr::arrange(g$data, colour_by)
g
```

**Comment by LTLA** [comment]
What's the point of this?

**Comment by robertamezquita** [comment]
Dealing with overplotting, so putting the things that actually have expression at the top

**Comment by LTLA** [comment]
Sounds dangerous, you would overstate the amount of expression in a region of the plot.

**Comment by kevinrue** [comment]
It's definitely not desirable to sort data points before plotting. It can introduce all sorts of bias in the interpretation, especially if readers are not aware of the sorting strategy and read the plot at face value.

A couple of strategies which address overplotting :
- summarisation: https://github.com/SaskiaFreytag/schex
- random downsampling by grid: https://github.com/csoneson/iSEE/blob/master/R/plotting.R#L630

**Comment by robertamezquita** [comment]
Good points. Maybe could look at porting the iSEE code over to the scater plotting functions...would also help with the overplotting problem. Anyways, closing the issue, thanks for the inputs!
