### ISSUE TITLE
Cannot install the latest version of scater

### ISSUE THREAD

**Issue by yewero** [alanocallaghan/scater#99]
I failed to install the latest version of scater:
`install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/scater_1.12.2.tar.gz")`
`ERROR: this R is version 3.5.1, package 'scater' requires R >= 3.6`

Is it possible to install it in R 3.5.1?

**Comment by LTLA** [comment]
No. Bioconductor packages are designed to work with a specific version of R, see [here](https://bioconductor.org/about/release-announcements/). You might think that this is pretty inconvenient, but it is the only way to guarantee that the packages work as advertised; R has many bugfixes and improvements at every release, so it's best practice to work with the latest version. In the past, when I was in a server environment with recalcitrant sysadmins, I would just install the latest version of R for myself on the server, and keep it up to date myself.

**Comment by yewero** [comment]
Thanks.
